golioth/golioth-firmware-sdk

examples/common/golioth_basics.c, examples/esp_idf/common/wifi.c, examples/modus_toolbox/golioth_basics/golioth_app/source/cy_flash_map.h, examples/modus_toolbox/golioth_basics/golioth_app/source/golioth_main.c, examples/modus_toolbox/golioth_basics/golioth_app/source/golioth_main.h, examples/modus_toolbox/golioth_basics/golioth_app/source/main.c, port/esp_idf/fw_update_esp_idf.c, port/esp_idf/libcoap/include/coap_config_posix.h, port/modus_toolbox/fw_update_mcuboot.c, port/modus_toolbox/libcoap/include/coap_config.h, port/modus_toolbox/libcoap/include/libcoap_posix_timers.h, port/modus_toolbox/libcoap/libcoap_posix_timers.c, port/modus_toolbox/libcoap/mbedtls_timing.c, scripts/lint/format_all_files.sh, src/golioth_coap_client.c, src/golioth_fw_update.c, src/golioth_lightdb.c
Ran scripts/lint/format_all_files.sh. Also fixed a stray 'j' character in the format_all_files.sh script.
=> apply clang-format to all source files

.github/workflows/lint_and_build.yml, .github/workflows/test_esp32s3.yml, README.md, examples/esp_idf/README.md
The latest ESP-IDF release is v4.4.2.
I tested the golioth_basics example with this version, and it worked without issue (no source code changes needed).
=> esp-idf: upgrade from v4.4.1 to v4.4.2

examples/esp_idf/test/main/app_main.c, examples/esp_idf/test/verify.py, src/golioth_rpc.c, src/golioth_settings.c
Relies heavily on Golioth API to create/delete/read settings. Test firmware modified to receive the TEST_SETTING setting and set the value received in LightDB state so it can be read via API and confirmed to match the original value.
Leaving the debug prints in verify.py since this is a new test and I'm not sure how stable/flaky it will be in CI.
=> test: add settings test

examples/modus_toolbox/README.md
The newest version of MTB (3.0.0) is not compatible with the example code (mostly Makefile and build system differences).
The differences between MTB 2.4.0 and 3.0.0 are entirely in the build system and don't affect the example C code.
For now, we will keep this example pinned to 2.4.0 for simplicity and ease of development. We link to the "official" MTB Golioth example which supports both 2.4.0 and 3.0.0.
=> MTB: README: requires MTB 2.4.0

src/golioth_coap_client.c
Previously, there was no way to differentiate between a handshake failure and a request timeout. The "Maybe your PSK-ID or PSK is incorrect?" message would display regardless, which is confusing in the timeout case, since normally the credentials are correct.
Libcoap has an internal state machine that will be in the "handshake" state, so use that to detect when the handshake is failed.
=> coap_client: detect handshake failures

port/esp_idf/components/golioth_sdk/CMakeLists.txt, port/esp_idf/libcoap/include/coap3/coap.h
Update to libcoap tip of main branch, which is release 4.3.1.
=> esp-idf: libcoap: update to 4.3.1

.github/workflows/lint_build_unit_test.yml, port/esp_idf/components/golioth_sdk/CMakeLists.txt, scripts/lint/check_clang_format.sh, src/priv_include/ringbuf.h, src/ringbuf.c, test/CMakeLists.txt, test/README.md, test/fff/CMakeLists.txt, test/fff/README.md, test/fff/fff.h, test/test.sh, test/test_ringbuf.c, test/unity/CMakeLists.txt, test/unity/README.md, test/unity/unity/unity.c, test/unity/unity/unity.h, test/unity/unity/unity_internals.h, test/unity/unity_config.h
Adds a generic ring buffer (intended for future use with remote shell feature).
Added a host unit testing framework so I could easily test ringbuf. This was something I had been meaning to do anyway, so now was a good time to do it. Unit tests are now checked in CI.
Copied files from unity and fff libraries in-tree, because it's only a handful of files and it's simpler than managing git submodules.
=> Add ringbuf.c and unit test framework

README.md
The new remote shell feature does not yet work on ModusToolbox, so it's a good excuse to make a table in the README with a list of features of the core SDK and whether they're supported on each platform.
Also, a capitalization fix and an update to the last tested version and date of ModusToolbox.
=> README: add feature x platform table

docs/Porting_Guide.md
Fixes misc. grammar and formatting issues
=> docs: fix typos in porting guide

README.md
Adding a :soon: status to indicate the features we will eventually implement.
=> README: use :soon: instead of :x: for TODO feature

examples/esp_idf/common/wifi.h, port/esp_idf/components/golioth_sdk/CMakeLists.txt, src/golioth_coap_client.c, src/golioth_debug.c, src/golioth_rpc.c, src/golioth_settings.c, src/include/golioth_debug.h, src/include/golioth_sys.h
Hexdump is useful for debugging.
Had to fix a few compilation errors related to usage of the
hexdump macro (previously were not compiled, so the errors
slipped through).
=> debug: implement hexdump macro

.github/workflows/test_esp32s3.yml
Currently, the workflow only runs on PRs and merges to main, meaning if there is no activity in this repo, it's possible a change to Golioth servers could have broken the end-to-end test.
Running a nightly test on a fixed schedule should help catch any serious issues within 24 hours, regardless of whether a PR has been created.
=> ci: run test_esp32s3.yml every night

.github/workflows/lint_build_unit_test.yml, examples/linux/README.md, port/linux/golioth_sdk/CMakeLists.txt
Previously, it was assumed the user would build and install libcoap to the system.
To make the build more self-contained and easier for users, libcoap is now built as part of the overall project via add_subdirectory.
=> linux: build libcoap from source

CONTRIBUTING.md, docs/Style_Guide.md
The intent is to be explicit about the style guidelines that matter to this project without be overly constraining.
The fallback style is Linux kernel style. We deviate from Linux kernel style in several significant ways, but these are mostly for conformance with existing code, not because our style is any better.
=> docs: add Style_Guide.md

README.md
This repo is cross-platform, so replace the bit about "connecting Espressif devices" to something more generic.
=> README: remove direct reference to Espressif

.github/workflows/firebase-doxygen-main.yml, .github/workflows/firebase-doxygen-pr.yml, .github/workflows/lint_build_unit_test.yml, .github/workflows/test_esp32s3.yml
This suppresses following warning:
> Node.js 12 actions are deprecated.
=> github-ci: update to actions/checkout@v3

examples/esp_idf/README.md, examples/esp_idf/common/shell.c
Previously, the file shell.c was based on the ESP-IDF example in ${IDF_PATH}/examples/system/console/advanced. This worked for most boards, but it did not work for the Adafruit ESP32-S2/S3 Feather boards, which use USB C and require CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG.
It turns out the ESP-IDF "basic" console examples are a better fit for what we need in shell.c, and they easily support CONSOLE_ESP_CONSOLE_{UART,USB_CDC,USB_SERIAL_JTAG} options, which should cover any ESP32 board.
Tested and confirmed the new shell.c works on the following boards:
ESP32-DevkitC
Magtag ESP32-S2,
Adafruit ESP32-S3 Feather
=> shell: follow IDF basic console configuration

docs/Integration_Guide.md
The ESP-IDF integration was missing a couple of steps about how to link the `golioth_sdk` into another component and what the app config should look like.
=> docs:integration: linking and config instructions

examples/esp_idf/common/wifi.c
The wifi module logs too much at the info level, so reduce the log level to WARN.
=> esp_idf:wifi: reduce log level to warn

examples/modus_toolbox/golioth_basics/golioth_app/Makefile, src/golioth_coap_client.c, src/golioth_fw_update.c
* Fixes a compilation error in Modus Toolbox (was missing heatshrink in Makefile)
* Fixes two printf-related warnings (one from Linux, one from Modus Toolbox)
=> Add missing heatshrink dep to MTB, fix misc compilation warnings

port/linux/golioth_sdk/CMakeLists.txt
If you don't include the quotes, the option value does not get applied.
=> port/linux: add missing quotes to cmake option

examples/esp_idf/certificate_auth/README.md
Support for certificates is now merged to the prod server (coap.golioth.io).
This updates the certificate_auth example README to reflect this.
=> esp_idf: examples: README fix for prod certificates

examples/esp_idf/certificate_auth/sdkconfig.defaults
Now that certificates are deployed on the prod server (coap.golioth.io), we can use the default value of CONFIG_GOLIOTH_COAP_HOST_URI (which is "coaps://coap.golioth.io") instead of overriding it in sdkconfig.defaults.
=> certificate_auth: use coap.golioth.io by default

port/esp_idf/components/golioth_sdk/CMakeLists.txt
Adding `nvs_flash` and `json` to the REQUIRE list of `golioth_sdk`.
The `json` component is required by the public SDK header `golioth_rpc.h` and the `nvs_flash` component is required by the public example headers in `examples/esp_idf/common`.
This makes it so external application can REQUIRE only `golioth_sdk`, without having to explicitly REQUIRE `json` or `nvs_flash`.
=> esp-idf: publicly require json and nvs_flash components

port/esp_idf/components/coap/CMakeLists.txt, port/esp_idf/components/golioth_sdk/CMakeLists.txt
Before this change, we named the libcoap component "libcoap" to avoid a name clash with ESP-IDF's libcoap component named "coap".
However, it's actually better to name the component the same as IDF does, because IDF will resolve the "coap" component to our component instead. It will only do this if the component is named identically:
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/build-system.html#multiple-components-with-the-same-name
This is important so that the SDK can build correctly in platformio. Otherwise, platformio will link IDF's "coap" component into the binary, which is older than the one we need, and contains a bug that will cause an issue with OTA downloads.
=> esp_idf: rename libcoap component to coap

docs/Flash_and_RAM_Usage.md
This doc represent a snapshot in time of the current flash and RAM usage of the SDK. This might be useful to system designers with a specific flash/RAM budget, to know how much will be used by the SDK.
=> docs: add Flash_and_RAM_Usage.md

src/golioth_debug.c, src/golioth_log.c
Before this change, any GLTH_LOGX statements longer than 100 characters
were getting silently dropped, because cJSON_PrintPreallocated failed to
serialize to the static buffer, which only had room for 100 characters.
Instead, we will let cJSON dynamically allocate the necessary storage
for us during serialization, and free it after adding it to the CoAP
client queue.
=> log: dynamically allocate serialized JSON strings

src/include/golioth_fw_update.h
Some users incorrectly assumed that golioth_fw_update_init() makes a string copy of the current_version parameter. This would cause later issues with firmware update, because current_version would be out of scope, causing undefined behavior due to invalid memory access.
Updating the docs to make this more explicit should help mitigate this kind of error.
=> fw_update: clarify that current_version is not deep-copied

src/golioth_fw_update.c, src/include/golioth_fw_update.h
This new API will allow the user to specify the name of the main firmware package, in case something other than "main" is desired.
Created a new golioth_fw_update_config_t struct which is passed into the new API, which may be helpful to maintain backward compatibility in case more user configuration parameters are added in the future.
=> fw_update: add golioth_fw_update_init_with_config()

src/golioth_fw_update.c
Firmware updates now support configurable package names. This commit adds the package name when the firmware version is reported in a log message.
=> fw_update: log package name along with fw version

docs/Integration_Guide.md
Shows the general procedure for adding Golioth to an existing MTB project.
It's not a full integration guide, but more of a "fuzzy" integration guide, showing general steps, but leaving out some of the details of how to add the MCUboot project and miscellaneous python and Makefile scripts for configuration of the flash map. This was done to keep the integration guide short and readable, and also because it's recommended for users to start from the Golioth example instead of trying to add Golioth SDK to an existing project.
=> docs: Add ModusToolbox to integration guide

examples/common/golioth_basics.c
The prior RPC named "double" was a little confusing to users. It was not clear what the RPC was intended to do, based on the name alone.
The double RPC is now replaced with "multiply", which is less confusing.
=> golioth_basics: change double RPC to multiply

port/linux/golioth_sys_linux.c
Before this change, the Linux implementation of golioth_sys_sem_take was not waiting long enough in the case where another signal is received, i.e. sem_timedwait return EINTR.
This fixes the issue by calling sem_timedwait in a loop if the errno is EINTR.
=> golioth_sys_linux: restart sem_timedwait on EINTR

src/golioth_coap_client.c
It seems that there is nothing actually using this header, so remove it.
=> coap_client: remove sys/socket.h

.github/workflows/firebase-doxygen-pr.yml, .github/workflows/test_esp32s3.yml
This check is no longer needed.
The original intent was to prevent self-hosted Actions Runner jobs from executing from fork pull requests, as a security measure to prevent remote code execution.
However, we have since disabled automatic execution of these jobs for PRs from outside collaborators in the GitHub repo settings (requires approval before running), so the guard in the .yml is not needed anymore.
=> .github: remove check for fork pull request

examples/esp_idf/README.md
Instead of invoking `git clone ...` on default branch, recursively cloning
all modules and then manually checking out latest release tag (v5.0)
followed by updating submodules, just do everything in one step by simply
providing `git clone ... -b v5.0`.
=> examples: esp_idf: clone and checkout all modules in one step

src/golioth_coap_client.c
libcoap introduced enums for log levels, so use those instead of abitrary
log level integer.
=> golioth_coap_client: use COAP_LOG_INFO instead of abitrary number

docs/Style_Guide.md
Before this change, there was no guidance on what an acceptable number of variables should be.
There are places in the SDK that already violate this style, but at least this can be used as guidance for future code changes.
=> Style_Guide: no more than 7 variables

port/linux/fw_update_linux.c
If a second firmware update is attempted, then the program will abort due to attempting to fclose(_fp) a second time.
Setting _fp to NULL after fclose() prevents it from being called a second time.
=> fw_update_linux: fix double-close of _fp

.github/workflows/test_esp32s3.yml
Previously, we relied on the repo secret GOLIOTH_API_KEY to be able to deploy the OTA release from GitHub Actions in the cloud.
This is problematic in the case where there are multiple self-hosted runners, each which might be using a different Golioth project with different API keys.
To resolve, we will deploy the OTA release from the self-hosted runner, where the runner-specific API key is already known and present in the file $HOME/credentials_esp32s3.yml.
This will allow for deleting the repo secret GOLIOTH_API_KEY.
=> .github: deploy new OTA release from self-hosted runner

examples/esp_idf/common/nvs.c
Before this change, the max number of characters that could be used
for the WiFi SSID and password was 31.
WPA2-PSK security allows for a PSK up to 32 characters in length,
so we should be able to accommodate PSKs of that length.
=> examples,nvs: increase max num chars for wifi params to 32

examples/esp_idf/test/main/app_main.c
test_connects_to_golioth() often fails due to a known bug on the backend that can cause the DTLS handshake to timeout (GB-564).
In a prior commit, the macro TEST_RESPONSE_TIMEOUT_S was introduced which sets the connect timeout to 2x + 1 seconds, where x is the timeout for a single request. This allows for one timeout to occur without failing the test.
It was intended that the test_connects_to_golioth() test use this macro, but it was overlooked/missed in the prior commit.
=> esp_idf/test: increase connect timeout to 2x resp timeout

src/golioth_coap_client.c
These are not used anywhere, and can be deleted from golioth_coap_client_t.
=> coap_client: remove unused psk and psk_len

port/esp_idf/libcoap/include/coap_config.h, port/modus_toolbox/libcoap/include/coap_config.h
Remove `COAP_RESOURCES_NOHASH` from our codebase, as it was deprecated in
libcoap back in 2018.
See: https://github.com/obgm/libcoap/commit/fbe1b8283d98fb796302a45dd442624e44642f91
=> port: remove COAP_RESOURCES_NOHASH definition

.github/workflows/test_esp32s3.yml
this presents a button on the GitHub actions page to manually trigger a hardware-in-the-loop (HIL) test on the esp32s3
=> add workflow-displatch to esp32s3 test

.github/workflows/firebase-doxygen-pr.yml
For PRs from forked pull requests, the `firebase-doxygen-pr.yml` workflow will fail with the following error:
```
/home/runner/work/_actions/FirebaseExtended/action-hosting-deploy/v0/bin/action.min.js:274
throw new Error(`Input required and not supplied: ${name}`);
^
```
This happens because the workflow does not have access to the repository secrets from the fork.
This is being resolved by changing the workflow to trigger on `pull_request_target`, which means it runs in the context of the base of the pull request, which has access to the repo secrets.
The workflow still requires approval from a Golioth team member to run, so from a security perspective, it will be as secure as it was before this commit.
More information is available here: …
=> .github: use "on: pull_request_target" for doxygen

README.md
Before this change, the features table indicated that Linux "OTA FW Update" was coming :soon:. However, other OTA features like compression and delta updates were already marked as supported, which was confusing, since one would expect the baseline FW update functionality to be a prerequisite for the other features.
This marks "OTA FW Update" as supported for Linux, but with a note that explains it is only partially implemented.
Fixes #101
=> README: clarify the support for OTA on Linux

port/esp_idf/libcoap/include/coap_config_posix.h
This way libcoap will use `pthread_mutex_*()` APIs from `pthread.h`. This
suppresses preprecessor `#warning` messages about mutex stubs.
Fixes: #78
=> port: esp_idf: define HAVE_PTHREAD_{H,MUTEX_LOCK}

port/esp_idf/components/golioth_sdk/Kconfig
This option was defined as `int`, but it actually is a only a boolean
option. Convert it to `bool`.
=> esp_idf: convert GOLIOTH_REMOTE_SHELL_ENABLE to bool

src/include/golioth_settings.h
Fixes the device_settings_register_bool docstring, which previously referred to itself. Both device_settings_register_bool and device_settings_register_float now refer to device_settings_register_int documentation.
=> fix: update device_settings_register_bool docstring

src/golioth_fw_update.c
Fixes the logging message on failure to create a firmware update thread, which previously referred to creating a shell thread, likely copied from the remote shell thread.
=> fix: emit accurate logging message on failure to create fw update thread

port/zephyr/golioth_fw_zephyr.c
Allow to transfer DFU artifact with disabled support for bootloader. This
makes it possible to test most DFU steps, with the only exception being
saving artifact to persistent storage (flash). This allows to test DFU with
`qemu_x86` (which does not have emulated flash storage) as well as
platforms like `nrf52840dk_nrf52840` with disabled bootloader
support (simplifies debugging, reduces flash wear, download latencies).
=> zephyr: dfu: allow most DFU steps with bootloader disabled

src/golioth_rpc.c, test/CMakeLists.txt, test/fakes/golioth_coap_client_fake.c, test/fakes/golioth_coap_client_fake.h, test/fakes/golioth_time_fake.c, test/fakes/golioth_time_fake.h, test/test.sh, test/test_golioth_rpc.c
Adds unit tests for the RPC module.
Also adds a set of fake functions for golioth_coap_client and golioth_time.
Also cleans up the Unit Test CMakeLists.txt and adds a convenience function for declaring unit tests.
=> unit_tests: Add RPC unit test

src/golioth_remote_shell.c
assert() is defined only after including assert.h.
=> remote_shell: include assert.h

examples/esp_idf/golioth_basics/README.md
Correct the golioth_basics README for esp-idf to indicate `CONFIG_GOLIOTH_REMOTE_SHELL_ENABLE` should be set to `y`, not `1`.
=> esp-idf: basics: Fix doc for remote shell enable

test/CMakeLists.txt
Doxygen build fails, since libcoap's `CMakeLists.txt` is included instead of
being the root file and specific (libcoap) folder structure is assumed.
Disable libcoap Doxygen build by forcing `ENABLE_DOCS` option to be `OFF`.
=> test: set ENABLE_DOCS to OFF to disable libcoap Doxygen build

port/esp_idf/components/golioth_sdk/CMakeLists.txt
=> port/esp_idf: Fix typo

port/zephyr/CMakeLists.txt
`../../src/include` is already included with `zephyr_include_directories()`,
which adds it to global scope. There is no reason to add it to (Golioth
SDK) library scope explicitly again.
=> zephyr: drop doubled include path

.gitmodules, docs/Integration_Guide.md, examples/modus_toolbox/golioth_basics/golioth_app/.cyignore, examples/modus_toolbox/golioth_basics/golioth_app/deps/cJSON.mtb, port/esp_idf/components/golioth_sdk/CMakeLists.txt, port/linux/golioth_sdk/CMakeLists.txt, port/zephyr/CMakeLists.txt, port/zephyr/Kconfig
cJSON library is not used anymore, since all common samples and services were convered to use zcbor library instead.
There is still a `magtag_demo` sample specific to ESP-IDF which uses cJSON. Since cJSON is provided by ESP-IDF itself, it will still work without issues.
Dropping cJSON from SDK allows to reduce maintenance on SDK development team as well as reduce number of 3rdparty projects that need to be cloned and mirrored by downstream projects.
=> drop cJSON as dependency

.github/workflows/gitlint.yml, .github/workflows/pre-commit.yml, .gitlint, .pre-commit-config.yaml, scripts/gitlint/commit_rules.py
There are few things that pre-commit checks, probably best described by
looking at the configured hooks documentation.
gitlint will allow for basic style check of commits messages. Add also
gitlint user defined check for Signed-off-by line.
This configuration was copied from Zephyr SDK.
=> ci: add pre-commit and gitlint workflows

src/golioth_coap_client.c, src/priv_include/golioth_coap_client.h
CoAP requests can be NACKed by libcoap stack for multiple reasons. The most
probable is `COAP_NACK_TOO_MANY_RETRIES`, which is triggered when network
medium goes down.
=> client: handle NACKed CoAP requests

.clang-format, .github/workflows/lint_build_unit_test.yml, scripts/lint/check_clang_format.sh, scripts/lint/ci_check_clang_format.sh
The main goal behind this PR was to update our clang-format rules to use 4 spaces for ContinuationIndentWidth instead of 8, to match the rest of our indentation widths. This exposed 2 issues that are also fixed in this PR:
- We were previously always checking the diff between `HEAD` and `origin/main` which meant that making a change to .clang-format could flag unrelated commits if the base branch for a PR wasn't `origin/main`.
- The script we use to run clang-format only on files in the git diff checked the whole file, instead of just the lines in the git diff. This could also result in clang-format flagging unrelated changes. Instead of our custom tooling, we can use `git-clang-format`, which is distributed alongside `clang-format` and already has the ability to only check the lines that …
=> Update indent rules

examples/zephyr/hello/sample.yaml, port/zephyr/Kconfig
CIPHERSUITES was added to Kconfig in a previous commit because it was used in the `hello` twister testing. However, those test cases were for features yet to be implemented. This removes the unused tests.
=> zephyr: remove CIPHERSUITES and unused tests

.gitignore
Ignore the `tags` files generated by ctags when indexing the source code
=> gitignore: ignore ctags

examples/zephyr/lightdb/get/src/main.c
The `golioth_lightdb_get_int_sync()` function specifies int32_t for return value (not uint32_t)
=> zephyr: lightdb get: fix variable type

src/golioth_ota.c, src/zcbor_utils.c, src/zcbor_utils.h
So far 0xA0 (as it is an empty map) was checked explicitly. Change that to
handling -ENOENT output from zcbor_map_decode(). This makes CBOR
details (such as processing A0 byte) be handled in CBOR (zcbor) utils,
while keeping 'ota' module using higher-level APIs.
=> ota: handle -ENOENT from zcbor_map_decode() in case of no releases

examples/linux/README.md, examples/linux/golioth_basics/main.c
Updates the Linux Golioth Basics example to source PSK and PSK ID from environment variables so that recompiling is not necessary to provide new credentials.
Fixes #149
=> linux: source PSK and PSK ID from environment

src/include/golioth_client.h
Drops a broken link to the documentation for CoAP authentication. Information is now provided under the device authentication page.
=> Remove broken link for CoAP auth

port/zephyr/libcoap/io.c
This assert is no longer relevant, and it fails to compile. It was likely left over from initial proof-of-concept work.
=> port: zephyr: remove broken assert

CHANGELOG.md, examples/common/golioth_basics.c, examples/esp_idf/test/main/app_main.c, src/golioth_remote_shell.c, src/golioth_rpc.c, src/include/golioth_rpc.h, test/test_golioth_rpc.c
Add `GOLIOTH_` to all RPC status names so that the format matches: `GOLIOTH_RPC_OK`
=> golioth_rpc_status_t: use GOLIOTH_ namespace

examples/zephyr/dfu/README.md, examples/zephyr/hello/README.md, examples/zephyr/lightdb/delete/README.md, examples/zephyr/lightdb/get/README.md, examples/zephyr/lightdb/observe/README.md, examples/zephyr/lightdb/set/README.md, examples/zephyr/lightdb_stream/README.md, examples/zephyr/logging/README.md, examples/zephyr/rpc/README.md
Add the pin mapping for using the ESP32-WROVER as an AT modem to the matrix that already shows mappings for the ESP32-WROOM in each README file.
=> examples: zephyr: add pin map for ESP32-WROVER

examples/zephyr/lightdb_stream/README.md
Adds pin mappings for using the ESP32-C3-MINI-1 for WiFi with ESP-AT.
=> Add pin mappings for ESP32-C3 ESP-AT example

examples/zephyr/common/net_connect.c
DORMANT state in case of WiFi means that interface is ready for WiFi mgmt commands, such as "WiFi connect". This means that such interface will not get into UP state automatically and it makes no sense to wait for that event.
Above behavior was introduced some time ago in Zephyr upstream, however none of the WiFi drivers were updated yet to follow this behavior (remaining in DORMANT state before connecting to Access Point). Since the first driver (ESP-AT) was converted in Zephyr mainline, add support for such behavior.
Originally made by @mniestroj in Zephyr SDK.
=> examples: zephyr: common: do not wait for dormant WiFi interface

examples/linux/certificate_auth/README.md, examples/linux/certificate_auth/golioth_user_config.h
Updates Linux example for cert auth to use new console flow and remove
disclaimer about production readiness.
Signed-off-by: Daniel Mangum <georgedanielmangum@gmail.com>
=> Update Linux example docs with production cert flow

examples/linux/README.md, examples/linux/golioth_basics/main.c, examples/modus_toolbox/README.md, examples/modus_toolbox/golioth_basics/golioth_app/source/credentials.inc.template, examples/modus_toolbox/golioth_basics/golioth_app/source/golioth_main.c, examples/modus_toolbox/golioth_basics/golioth_app/source/golioth_main.h, examples/zephyr/README.md
Updates all remaining credential symbols that do not use the GOLIOTH_SAMPLE_* prefix convention.
=> Use consistent symbols for sample credentials

README.md
- Add links to quick start READMEs for each port.
- Add note that `west` should be used to check out code for Zephyr port
- Remove "supported features" table - it was out of date and confusing. Going forward, all ports will support the same feature set.
=> readme: update the way we talk about ports

.github/workflows/firebase-doxygen-pr.yml, README.md, examples/zephyr/dfu/README.md, examples/zephyr/hello/README.md, examples/zephyr/lightdb/delete/README.md, examples/zephyr/lightdb/get/README.md, examples/zephyr/lightdb/observe/README.md, examples/zephyr/lightdb/set/README.md, examples/zephyr/lightdb_stream/README.md, examples/zephyr/logging/README.md, examples/zephyr/rpc/README.md, examples/zephyr/settings/README.md
We were previously running the doxygen workflow on the target branch, which isn't helpful. As a result a few bugs made it through.
- Test doxygen on PR branch
- Remove broken links
- Use Markdown formatted codeblocks instead of RST
=> Docs fixes

examples/zephyr/lightdb/delete/README.md
Update README to show this example deletes the state endpoint.
=> examples: zephyr: fix lightdb delete description

examples/modus_toolbox/golioth_basics/golioth_app/Makefile, port/zephyr/CMakeLists.txt, src/golioth_ota.c, src/golioth_rpc.c, src/golioth_settings.c, src/zcbor_any_skip_fixed.c, src/zcbor_any_skip_fixed.h, src/zcbor_utils.c
Backport fixed zcbor_any_skip() from zcbor 0.7.0.
This fix was originally implemented by @mniestroj in https://github.com/golioth/golioth-zephyr-sdk/commit/e6a6117.
=> zcbor: backport zcbor_any_skip() for zcbor < 0.7.0

examples/zephyr/common/Kconfig
Removes the dependency on BOOTLOADER_MCUBOOT for GOLIOTH_SAMPLE_FW_VERSION as it breaks DFU samples that do not use mcuboot.
Before this change I was seeing:
```
/home/hasheddan/code/github.com/golioth/golioth-firmware-sdk/examples/zephyr/dfu/src/main.c:18:39: error: 'CONFIG_GOLIOTH_SAMPLE_FW_VERSION' undeclared here (not in a function); did you mean 'CONFIG_GOLIOTH_SAMPLE_COMMON'?
18 | static const char* _current_version = CONFIG_GOLIOTH_SAMPLE_FW_VERSION;
|                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|                                       CONFIG_GOLIOTH_SAMPLE_COMMON
[148/396] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/net_context.c.obj
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: …
```
=> examples: zephyr: remove sample firmware version dependency on mcuboot

.github/workflows/lint_build_unit_test.yml
Updates lint workflow to use commit prior to push when merging to main. Previously the step would fail because $GITHUB_BASE_REF is empty.
See https://docs.github.com/en/webhooks/webhook-events-and-payloads#push:~:text=or%20null%20Required-,before,-string%20Required for more information.
Fixes golioth/firmware-issue-tracker#248
=> ci: use previous commit for linting on main

.github/workflows/lint_build_unit_test.yml
Sets the fetch depth for linting to 10, which serves as a reasonable upper bound for the number of commits in a single PR. If the default fetch-depth of 1 is used, we are unable to calculate files changed as part of a PR being merged.
Follow-up to https://github.com/golioth/golioth-firmware-sdk/pull/189
=> ci: increase fetch depth for linting

examples/zephyr/dfu/README.md
The instructions are to build the update image with version 1.2.4, but the upload instructions use version 1.2.3. This commit changes the upload instructions to match the version number that gets built.
=> examples: zephyr: dfu: fix version number in readme

examples/zephyr/lightdb/delete/README.md, examples/zephyr/lightdb/get/README.md, examples/zephyr/lightdb/observe/README.md, examples/zephyr/lightdb/set/README.md, examples/zephyr/lightdb_stream/README.md
Fixes paths in the zephyr examples that were referencing the no longer
existent samples directory.
Signed-off-by: Daniel Mangum <georgedanielmangum@gmail.com>
=> examples: zephyr: fix example paths

examples/zephyr/README.md
When adding the Golioth Firmware SDK to an existing West manifest, use the submodules keyword to automatically update git submodules. This eliminates the need to manually call `git submodule <subcommand>` commands.
Note: this will not work when the Firmware SDK is used as the manifest repository.
=> zephyr: use submodules keyword in manifest

src/include/golioth_client.h
Updates stale references to using PEM encoded certs to properly reflect that certs are now DER encoded.
Follow-up to #145
=> docs: auth: update PEM to DER

.github/workflows/lint_build_unit_test.yml, .github/workflows/twister-build.yml
Creates a reusable workflow for running twister build tests on a single board, with either Zephyr or NCS. Uses this workflow to run build tests on each of our CVBs. Because these are run as separate steps in the caller workflow, they run in parallel on separate runners, and complete faster than if they were run sequentially.
Resolves golioth/firmware-issue-tracker#281
=> ci: parallelize twister builds

.github/workflows/firebase-doxygen-main.yml, .github/workflows/firebase-doxygen-pr.yml, .github/workflows/gitlint.yml, .github/workflows/lint_build_unit_test.yml, .github/workflows/pre-commit.yml, .github/workflows/test_esp32s3.yml, .github/workflows/twister-build.yml
Several of the actions that we use in CI are out of date and GitHub throws warnings when they are run, due to running on a deprecated node. This updates the actions to their latest versions.
=> ci: update actions

examples/zephyr/common/include/samples/common/sample_credentials.h
Document that golioth_sample_credentials_get() can return credentials from one of three sources.
=> zephyr: common: document credentials_get

.ci-west-ncs.yml, .ci-west-zephyr.yml, .github/workflows/lint_build_unit_test.yml, .github/workflows/twister-build.yml
A couple small improvements to speed up build times:
Twister defaults to using twice the number of CPU cores when running build-only tests. Ninja also uses the number of CPU cores for building, meaning we could have 2\*N\*N (8 in our case) threads compiling simultaneously, which leads to bottlenecks and slows down builds. Experimentally, limiting twister to 2 threads (from a default of 4) results in the fastest build times.
We only need a subset of the projects that are in the main Zephyr and NCS West manifests in order to build our samples and tests. By using a manifest that only downloads the projects that we actually need, we can speed up our CI build times.
=> Ci Improvements

docs/doxygen/Doxyfile
After updating our include path, the Doxygen site is now showing information for the private functions instead of the user API.
Include path for APIs was moved up one directory. This commit changes Doxygen to match.
=> doxygen: update include path

examples/zephyr/common/Kconfig.defconfig
Closes golioth/firmware-issue-tracker#283
=> examples: zephyr: enable reboot by default

.github/workflows/twister-build.yml
The official Zephyr CI Docker image is rather large, and includes many toolchains, modules, and other things that we don't need for our own builds. Using our own, smaller Docker image in CI can cut the time it takes to download and initialize the container from about 2-2.5 minutes down to about 30 seconds. This container does not come pre-installed with Zephyr's required python dependencies so this also adds a step in the CI workflow to install them, which is more robust anyway.
=> ci: use minimal docker image for build test

.github/workflows/twister-build.yml
Twister treats overflows in the RAM during builds as "skipped" tests instead of errors by default. Enabling the `--overflow-as-errors` option ensures we can catch overflows in CI.
Fixes golioth/firmware-issue-tracker#296
=> ci: catch ram overflow build failures

examples/zephyr/dfu/README.md, examples/zephyr/golioth_basics/README.md
* Add --sysbuild in DFU for esp32
* Add --sysbuild in golioth_basics for esp32 and nrf52840
* Document rebuilding for firmware update in golioth_basics
=> examples: zephyr: add --sysbuild to README files

examples/zephyr/hello/sample.yaml, port/zephyr/Kconfig, port/zephyr/libcoap/coap_io_zephyr.c
Whether enabling connection IDs is beneficial or harmful is dependent on the application, so do not enable them by default. Instead, add a new Kconfig option for using connection IDs.
=> port: zephyr: disable cid by default

examples/zephyr/README.md
Removes reference to non-existent west-external.yml.
This currently causes `west update` to break when adding `golioth-firmware-sdk` to existing projects.
=> examples: zephyr: remove reference to west-external.yml

.github/workflows/hil_test.yml, tests/hil/scripts/pytest-hil/board.py, tests/hil/scripts/pytest-hil/nordicboard.py, tests/hil/scripts/pytest-hil/nrf52840dk.py, tests/hil/scripts/pytest-hil/plugin.py, tests/hil/scripts/pytest-hil/pyproject.toml
Add the ability to program DUTs through the pytest-hil fixture, so that device specific programming logic can be removed from the GitHub Actions workflow yaml.
Closes golioth/firmware-issue-tracker#304
=> tests: add program method to pytest hil fixture

tests/hil/scripts/pytest-hil/pyproject.toml
pyserial and PyYAML were implicit dependencies of the pytest-hil package. This makes them explicit.
=> pytest-hil: specify additional dependencies

.github/workflows/hil_tests.yml
The default GitHub Actions behavior is to cancel all other jobs spawned from a matrix when one of the jobs fails. This means our HIL tests are only able to identify at most one failure. Specifying `fail-fast` as false allows all jobs to complete even if one fails, giving us a more complete picture of how many tests are passing or failing.
=> ci: don't cancel other hil tests when one fails

.github/workflows/hil_test_esp-idf.yml, .github/workflows/hil_test_zephyr.yml, .github/workflows/hil_tests.yml
Run our HIL tests on the ESP32-DevKitC-WROVER board (running ESP-IDF) in CI.
Closes golioth/firmware-issue-tracker#310
=> ESP32-DevKitC-WROVER (ESP-IDF) HIL test

.github/workflows/hil_test_esp-idf.yml, .github/workflows/hil_test_zephyr.yml, .github/workflows/test_esp32s3.yml, tests/hil/tests/connection/test_connection.py
* Use docker for all HIL testing on this repo
* Specifically target on self-hosted runner for the legacy esp32s3 test to workaround timeouts on some runners. This is being phased out and will soon be replaced with more granular tests
Changing to Docker HIL images was tested before opening this PR:
* https://github.com/golioth/golioth-firmware-sdk/actions/runs/7089709731
* https://github.com/golioth/golioth-firmware-sdk/actions/runs/7067511221
* https://github.com/golioth/golioth-firmware-sdk/actions/runs/7066696608
=> Use docker for hil tests

tests/hil/scripts/pytest-hil/pyproject.toml
Hatch now throws an error if files are not selected are not supplied to wheel. This commit includes all python files to satisfy the new condition.
Read more: https://github.com/pypa/hatch/issues/1113
=> tests: fix breaking change in hatch python package

port/zephyr/Kconfig, port/zephyr/include/golioth_port_config.h
Add a kconfig option for CONFIG_GOLIOTH_LOG_LEVEL so users can control the verbosity of internal SDK logs.
Resolves golioth/firmware-issue-tracker#319
=> port: zephyr: add kconfig for default log level

.editorconfig
Update the .editorconfig to reflect the indent we're using in practice.
=> editorconfig: use indent of 2 for yaml

examples/zephyr/hello/pytest/conftest.py, examples/zephyr/hello/pytest/test_sample.py, examples/zephyr/hello/sample.yaml
Add a pytest-based Twister test to the Hello sample:
* Compile and flash the sample to each HIL board
* Monitor the board's serial connection for the fourth Hello message to be sent
* Query the device logs from Golioth and search them backwards for the first three Hello messages
This test ensures the following:
* By waiting until the fourth message has been sent, we have a built-in 5 second window for the previous Hello message to arrive on the server and be available via the Rest API
* When searching the logs we verify all of the first three Hello messages were received in the order they were sent.
=> zephyr: add test for hello sample

examples/zephyr/rpc/pytest/conftest.py, examples/zephyr/rpc/pytest/test_sample.py, examples/zephyr/rpc/sample.yaml
Check for successful integer result, float results, and verify error code when an invalid parameter type is supplied.
=> zephyr: add test for rpc sample

.github/workflows/hil_sample_zephyr.yml, .github/workflows/hil_test_esp-idf.yml, .github/workflows/hil_test_zephyr.yml
Update Docker images for Twister and HIL base to newest which include USB hub control. Call the script to power cycle the hub before running tests.
=> HIL: reset USB hub before running tests

.github/workflows/hil_sample_zephyr.yml, .github/workflows/hil_test_esp-idf.yml, .github/workflows/hil_test_zephyr.yml, .github/workflows/test_esp32s3.yml
Require the is_active lable when selecting a self-hosted runner. This label indicates the runner is available for testing. The label will be removed from runners undergoing maintenance.
=> HIL: use is_active label with runners

src/golioth_rpc.c, src/golioth_settings.c
There's no reason to provide a noop function for a disabled SDK service. Instead, we should not provide implementations for disabled functions at all, so that if a user attempts to call these functions the build will fail at link time.
Fixes golioth/firmware-issue-tracker#355
=> Ensure disabled services fail to link

examples/zephyr/lightdb/delete/pytest/conftest.py, examples/zephyr/lightdb/delete/pytest/test_sample.py, examples/zephyr/lightdb/delete/sample.yaml, examples/zephyr/lightdb/get/pytest/conftest.py, examples/zephyr/lightdb/get/pytest/test_sample.py, examples/zephyr/lightdb/get/sample.yaml, examples/zephyr/lightdb/get/src/main.c, examples/zephyr/lightdb/observe/pytest/conftest.py, examples/zephyr/lightdb/observe/pytest/test_sample.py, examples/zephyr/lightdb/observe/sample.yaml, examples/zephyr/lightdb/set/pytest/conftest.py, examples/zephyr/lightdb/set/pytest/test_sample.py, examples/zephyr/lightdb/set/sample.yaml
Add Twister tests for each of the LightDB State samples. Also includes a little bit of cleanup of error handling in the lightdb/get sample.
Resolves golioth/firmware-issue-tracker#274
=> Lightdb state example tests

.github/workflows/hil_sample_zephyr.yml, examples/zephyr/hello/pytest/conftest.py, examples/zephyr/hello/pytest/test_sample.py, examples/zephyr/lightdb/delete/pytest/conftest.py, examples/zephyr/lightdb/delete/pytest/test_sample.py, examples/zephyr/lightdb/get/pytest/conftest.py, examples/zephyr/lightdb/get/pytest/test_sample.py, examples/zephyr/lightdb/observe/pytest/conftest.py, examples/zephyr/lightdb/observe/pytest/test_sample.py, examples/zephyr/lightdb/set/pytest/conftest.py, examples/zephyr/lightdb/set/pytest/test_sample.py, examples/zephyr/lightdb_stream/pytest/conftest.py, examples/zephyr/lightdb_stream/pytest/test_sample.py, examples/zephyr/logging/pytest/conftest.py, examples/zephyr/logging/pytest/test_sample.py, examples/zephyr/rpc/pytest/conftest.py, examples/zephyr/rpc/pytest/test_sample.py, examples/zephyr/settings/pytest/conftest.py, examples/zephyr/settings/pytest/test_sample.py
Using the golioth pytest plugin (introduced in https://github.com/golioth/python-golioth-tools/pull/7) reduces the amount of boilerplate code that needs to be copy and pasted
between test cases.
Resolves golioth/firmware-issue-tracker#357
=> examples: pytest: use golioth pytest plugin

examples/common/golioth_basics.c, examples/esp_idf/test/main/app_main.c, examples/zephyr/rpc/src/main.c, examples/zephyr/settings/src/main.c, include/golioth/rpc.h, include/golioth/settings.h, src/coap_client.c, src/coap_client.h, src/lightdb_state.c, src/lightdb_stream.c, src/rpc.c, src/settings.c, tests/unit_tests/fakes/coap_client_fake.c, tests/unit_tests/fakes/coap_client_fake.h, tests/unit_tests/test_rpc.c
The coap_client module should not have any knowledge of the services built on top of it. Remove the settings and rpc structs from the coap_client and instead create init functions that creates the state structs for each, adds a pointer to the client, and returns the struct to the user.
Resolves golioth/firmware-issue-tracker#370
=> Remove circular references between services and coap_client

examples/zephyr/common/Kconfig, examples/zephyr/common/nrf91_lte_monitor.c, examples/zephyr/hello/sample.yaml, examples/zephyr/lightdb/delete/sample.yaml, examples/zephyr/lightdb/get/sample.yaml, examples/zephyr/lightdb/observe/sample.yaml, examples/zephyr/lightdb/set/sample.yaml, examples/zephyr/lightdb_stream/sample.yaml, examples/zephyr/logging/sample.yaml, examples/zephyr/rpc/sample.yaml, examples/zephyr/settings/sample.yaml
The nrf91 modem has a built in reset loop restriction that activates when the device is reset 7 times in a row within 30 seconds of connecting to the network. This restriction prevents the modem from connecting to the network for 30 minutes. We hit this frequently during CI. This PR monitors for an event from the modem that indicates the reset loop is active and notifies the user when the event is received. It also adds a Kconfig option to automatically factory reset the modem when we enter the reset loop. This removes the reset loop restriction and lets the modem start working immediately, but is not recommended in production because a) it may just send you back into the reset loop and b) factory reset writes to flash and so has flash wear implications. Neither of these apply to us in CI …
=> Detect and fix modem reset loop

examples/zephyr/settings/sample.yaml
When running the twister test on the nrf9160dk, it can take some time to connect to the cellular network. This can cause the test to hit the twister default timeout of 60s. Extending the timeout to 90 seconds should give the test enough time to complete successfully.
Fixes golioth/firmware-issue-tracker#373
=> examples: zephyr: settings: extend twister timeout

.github/workflows/hil_sample_zephyr.yml, examples/zephyr/hello/pytest/test_sample.py, examples/zephyr/lightdb/delete/pytest/test_sample.py, examples/zephyr/lightdb/get/pytest/test_sample.py, examples/zephyr/lightdb/observe/pytest/test_sample.py, examples/zephyr/lightdb/set/pytest/test_sample.py, examples/zephyr/lightdb_stream/pytest/test_sample.py, examples/zephyr/logging/pytest/test_sample.py, examples/zephyr/rpc/pytest/test_sample.py, examples/zephyr/settings/pytest/test_sample.py
Instead of relying on files existing on disk to get the PSK-ID and PSK, instead pull credentials from the Golioth REST API. This is done through the `device` fixture provided by the Golioth pytest plugin.
Resolves golioth/firmware-issue-tracker#358
=> examples: zephyr: pull psk from rest api for tests

.github/workflows/hil_sample_zephyr.yml
Don't provide the `GOLIOTH_DEVICE_NAME` environment variable to the twister tests. This will cause the golioth pytest plugin to automatically generate a temporary device in the console to use for the duration of the test, after which it will be deleted. Using automatically generated devices reduces the amount of manual work needed to add a device into the HIL runners (we no longer need to manually create devices) and will make it easier to move to a different project or backend environment in the future.
This uses the functionality provided by golioth/python-golioth-tools#9 and golioth/python-golioth-tools#10
Resolves golioth/firmware-issue-tracker#326
=> ci: use auto-generated boards for twister tests

.github/workflows/lint_build_unit_test.yml
The latest version of `gdown` has a regression that prevents us from being able to download the Modus Toolbox package. Pin `gdown` to 4.6.0 to avoid the regression.
Fixes golioth/firmware-issue-tracker#375
=> ci: pin version of `gdown` package

.github/workflows/test_esp32s3.yml
Use device tag when creating release so that it doesn't interfere with other OTA tests that may run at the same time.
=> workflows: use tag for legacy esp-idf test

examples/zephyr/common/Kconfig.defconfig
* Increase the max eventfd to avoid ENOMEM error in fw_update example
* Increase the total file descriptors to match, avoiding ENFILE error
We should consider moving this out of examples/zephyr/common and into the defconfig for the SDK as it will be needed whenever firmware update is selected.
(edit: I just force-pushed to fix the name of the error in the commit message)
=> examples: zephyr: increase fd for fw update

.github/workflows/hil_sample_zephyr.yml, examples/zephyr/hello/sample.yaml, examples/zephyr/lightdb/delete/sample.yaml, examples/zephyr/lightdb/get/sample.yaml, examples/zephyr/lightdb/observe/sample.yaml, examples/zephyr/lightdb/set/sample.yaml, examples/zephyr/lightdb_stream/sample.yaml, examples/zephyr/logging/sample.yaml, examples/zephyr/rpc/sample.yaml, examples/zephyr/settings/sample.yaml
Testing against prod most closely mirrors what devices will experience in the field, and also isolates our tests from any instability in the dev environment.
Resolves golioth/firmware-issue-tracker#325
=> ci: test against prod backend environment

examples/zephyr/hello/sample.yaml
Add a Hardware in the Loop test that uses connection ID for the Hello sample.
=> zephyr: CI: add Hello test using CID

.github/workflows/hil_sample_zephyr.yml, .github/workflows/hil_test_zephyr.yml, .github/workflows/lint_build_unit_test.yml
cryptography 42.0.0 breaks the modus toolbox build so pin the version to 41.0.7
Fixes https://github.com/golioth/firmware-issue-tracker/issues/396
=> pin cryptography pip package version

.github/workflows/hil_sample_zephyr.yml, .github/workflows/hil_test_esp-idf.yml, .github/workflows/hil_test_zephyr.yml, .github/workflows/lint_build_unit_test.yml, .github/workflows/test_esp32s3.yml
Node16 has been deprecated by GitHub. Update all of our actions to the latest version so that they use Node20.
Resolves golioth/firmware-issue-tracker#400
=> ci: update github actions versions

CHANGELOG.md, examples/zephyr/lightdb_stream/src/main.c, include/golioth/stream.h, src/stream.c
Remove the `golioth_stream_set_cbor_async/sync` and `golioth_stream_set_json_async/sync` functions and replace them with `golioth_stream_set_async/sync` function that requires a `golioth_content_type` as an argument.
This makes it possible to add more content types in the future without introducing breaking changes.
=> stream: use golioth_content_type to set objects

docs/doxygen/Doxyfile
The root url was specified by / but needs to be the actual url of the host site.
=> doxygen: fix root url used by sitemap

examples/zephyr/certificate_provisioning/src/main.c
We were waiting for the connected semaphore twice, which results in the example hanging forever on the second sem wait.
Fixes golioth/firmware-issue-tracker#416
Fixes golioth/firmware-issue-tracker#410
=> examples: zephyr: certificate_provisioning: fix deadlock

src/settings.c
Previously, when a user registered a setting with the SDK, the value of that setting would not be updated until the next time it was changed in the console. Instead, when a user registers a setting with the settings service, we should request the settings object from the backend so that we can update the callbck with the latest setting value.
Fixes golioth/firmware-issue-tracker#413
=> settings: GET settings after each registration

examples/zephyr/lightdb/delete/src/main.c, examples/zephyr/lightdb/get/src/main.c, examples/zephyr/lightdb/observe/src/main.c, examples/zephyr/lightdb/set/src/main.c
The lightdb examples were using a 1 second timeout for synchronous operations, which we can hit quite often on a cell network. Extending the timeout to 5 seconds should be more than sufficient.
=> examples: zephyr: lightdb: extend timeout

src/coap_client_zephyr.c, src/coap_client_zephyr.h
The `pending_req` member is a relic from libcoap and not used in the Zephyr coap client implementation.
=> coap_client_zephyr: remove unused client struct member

port/zephyr/golioth_log_zephyr.c, src/coap_client.c
If we got too many logs at once, we would hang both the coap_client thread and the logging thread. This fixes both, details in the commit messages.
=> Fix logging

docs/Migration_Guide_Zephyr.md
`golioth_client_config_t` was changed to `struct golioth_client_config` in the latest release.
=> Docs: use structs not typdefs in migration guide

tests/hil/scripts/pytest-hil/board.py
The pytest-hil package uses serial.readline() in a loop to wait for strings. Each iteration through the loop, we check for a timeout. But serial.readline() itself has no timeout and so if we receive no input at all, we will never check the timeout and hang forever. This happens sometimes when the serial port gets locked up (e.g. on the mimxrt1024).
Fixes golioth/firmware-issue-tracker#424
=> pytest-hil: respect timeout when waiting for serial input

examples/zephyr/common/hardcoded_credentials.c
Fix following build error when used with `native_sim`:
```
/hardcoded_credentials.c:51:35: error: initializer element is not constant
51 |         .psk_id_len = strlen(CONFIG_GOLIOTH_SAMPLE_PSK_ID),
|                       ^~~~~~
```
by replacing `strlen()` with `sizeof() - 1`.
=> examples: zephyr: hardcoded_credentials: replace strlen() with sizeof()

src/zephyr_coap_req.c
Fix undefined behavior related to `free()` of uninitialized pointer. Just
return early when allocation with `golioth_coap_req_new()` has failed.
=> zephyr: coap_req: do not free unallocated 'coap_req'

.github/workflows/hil_tests.yml
The nrf9160dk is using up unexpectedly large amounts of cell data. We'll disable these tests until we can determine the cause of the data spike and fix it.
=> ci: disable 9160 HIL tests

src/coap_client_libcoap.c
`purge_request_mbox()` was moved to `coap_client.c` but an implementation still exists in `coap_client_libcoap.c`. This implementation isn't called anywhere, and so it can be removed.
=> libcoap: remove unused function

port/esp_idf/components/golioth_sdk/CMakeLists.txt, port/esp_idf/golioth_port_config.h, src/coap_client_libcoap.c
ESP-IDF disables some compiler warnings and errors that are useful and should not be ignored. This commit explicitly enables some warnings and errors for the SDK component and fixes the warnings/errors that doing so revealed.
Resolves golioth/firmware-issue-tracker#441
=> [ESP-IDF] Enable compiler warnings errors

.github/workflows/hil_sample_zephyr.yml, .github/workflows/hil_test_esp-idf.yml, .github/workflows/hil_test_zephyr.yml, examples/zephyr/fw_update/pytest/conftest.py, examples/zephyr/fw_update/pytest/test_sample.py, examples/zephyr/hello/pytest/conftest.py, examples/zephyr/hello/pytest/test_sample.py, examples/zephyr/lightdb/delete/pytest/conftest.py, examples/zephyr/lightdb/delete/pytest/test_sample.py, examples/zephyr/lightdb/get/pytest/conftest.py, examples/zephyr/lightdb/get/pytest/test_sample.py, examples/zephyr/lightdb/observe/pytest/conftest.py, examples/zephyr/lightdb/observe/pytest/test_sample.py, examples/zephyr/lightdb/set/pytest/conftest.py, examples/zephyr/lightdb/set/pytest/test_sample.py, examples/zephyr/lightdb_stream/pytest/conftest.py, examples/zephyr/lightdb_stream/pytest/test_sample.py, examples/zephyr/logging/pytest/conftest.py, examples/zephyr/logging/pytest/test_sample.py, examples/zephyr/rpc/pytest/conftest.py, examples/zephyr/rpc/pytest/test_sample.py, examples/zephyr/settings/pytest/conftest.py, examples/zephyr/settings/pytest/test_sample.py, tests/hil/scripts/pytest-hil/board.py, tests/hil/scripts/pytest-hil/plugin.py
This pulls WiFi credentials for each runner from GitHub secrets, instead of using prepositioned config files on the runners. With this is in place, we're almost ready to retire the configuration files, only the legacy `Test on Hardware` workflow still uses them.
The last commit is rather large, but it's making the same small change for each Zephyr sample.
Resolves golioth/firmware-issue-tracker#359
=> Get wifi from gh secrets

examples/zephyr/common/Kconfig, examples/zephyr/common/Kconfig.defconfig, port/zephyr/Kconfig
So far `examples/zephyr/common/Kconfig.default` was sourced at the
beginning of `examples/zephyr/common/Kconfig`. The latter was source
however at the end of `port/zephyr/Kconfig`. This means that any default
values inside of `port/zephyr/Kconfig` could not be overridden.
Source `Kconfig.default` at the beginning of `port/zephyr/Kconfig`, so that
all SDK Kconfig options can be overridden.
Provide a default entry for `GOLIOTH_COAP_HOST_URI`, so environment variable
with that name (if defined) will override default value.
This is useful for testing with self-hosted backend instances.
=> zephyr: allow to override GOLIOTH_COAP_HOST_URI from env

.github/workflows/hil_sample_zephyr.yml
If the `zephyr` folder already exists, west will leave local modifications to the tree. This can cause issue because other workflows can sometimes leave the tree in a bad state. Removing the folder before running `west update` ensures that west will always clone a fresh copy of the repository.
Fixes golioth/firmware-issue-tracker#446
=> ci: delete `zephyr` folder before `west update`

.github/workflows/hil_test_esp-idf.yml, .github/workflows/hil_test_zephyr.yml, tests/hil/scripts/pytest-hil/board.py
The rt1024 connection test sometimes hangs forever, despite read timeouts on the serial device. This is because the serial device was hanging up on _writes_. This PR adds a write_timeout to the serial device so the test will fail if the device becomes locked up.
As an additional precaution, this also installs and uses the `pytest-timeout` pytest plugin to add a 10 minute overall timeout to each test. 10 minutes is more than enough for our current tests, and will catch any other infinite loops or hangs that may occur.
Fixes golioth/firmware-issue-tracker#424
=> ci: fix infinite hangs

examples/zephyr/certificate_provisioning/pytest/test_sample.py
The device can bootup and begin running the sample before the test starts. This can cause us to miss the startup message. Reset the device at the beginning of the test to ensure we start from a known point.
Fixes golioth/firmware-issue-tracker#449
=> examples: zephyr: cert_prov: reset at test start

src/settings.c
The Settings API allows users to specify a minimum and maximum value for integer type settings. However, we weren't actually enforcing these limits.
Fixes golioth/firmware-issue-tracker#455
=> settings: check if int type settings are within range

src/settings.c
If we cannot find a registered setting with the key that we receive from the backend, then we should respond with `GOLIOTH_SETTINGS_KEY_NOT_RECOGNIZED` instead of `GOLIOTH_SETTINGS_VALUE_FORMAT_NOT_VALID`.
Fixes golioth/firmware-issue-tracker#456
=> settings: fix error code for unrecognized key

.github/workflows/hil_sample_zephyr.yml, .github/workflows/hil_test_esp-idf.yml, .github/workflows/hil_test_trigger.yml, .github/workflows/hil_test_zephyr.yml, .github/workflows/hil_tests.yml
This commit provides the option of specifying the API URL, API Key (through GitHub secret name) and CoAP gateway URI to use when triggering HIL tests through the GitHub Actions UI. Together, these options allow targeting the tests against different Golioth backend environments, such as the Dev environment. By default, tests will continue to run against the Production environment.
Inputs (including default values) are only available when the workflow has been either called by another workflow or manually dispatched. So to ensure that the HIL workflow continues to run nightly and on pushes to PRs, there is now a separate workflow that is trigger by schedule, PR and pushes to `main` that calls the HIL tests workflow, which takes input as described above.
Additionally, the GitHub actions UI …
=> ci: parameterize backend environment target for HIL tests

.github/workflows/hil_sample_zephyr.yml
Use `--prep-artifacts-for-testing` to reduce the size of the artifacts that are transferred between the build and test jobs in the workflow.
We couldn't use this before because of a bug when using sysbuild with twister that @szczys fixed in Zephyr 3.6.
Resolves golioth/firmware-issue-tracker#465
=> ci: reduce artifact size for twister tests

.github/workflows/hil_test_esp-idf.yml
The setup_python step isn't necessary to build the ESP-IDF tests (we don't use Python for this job). Removing the setup step saves nearly a minute in build time.
=> ci: esp-idf-test: remove setup_python step

.github/workflows/hil_sample_esp-idf.yml, .github/workflows/hil_tests.yml
Adds a new workflow for testing ESP-IDF samples. This workflow automatically finds, builds, and tests samples as they are added by looking for directories under `examples/esp-idf` that contain a `pytest` folder.
Resolves golioth/firmware-issue-tracker#436
=> ci: test esp-idf samples

docs/Style_Guide.md, include/golioth/client.h, include/golioth/lightdb_state.h, include/golioth/ota.h, include/golioth/payload_utils.h, include/golioth/rpc.h, include/golioth/settings.h, include/golioth/stream.h
`@retval` expects the first token to be a literal value, and renders it as code in the docs. This looks a little nicer than `@return` both in our generated docs and most code completion tools.
This PR changes the return value description to `@retval` for all functions that only list return values, but keeps the ones that still have a mix as-is.
[Example from Zephyr docs](https://docs.zephyrproject.org/latest/doxygen/html/group__memory__attr__heap.html#ga85301dfc19493a84e89f965ed793d576).
`@return`:
`@retval`:
=> Use `@retval` instead of `@return` when relevant

examples/zephyr/common/Kconfig, examples/zephyr/common/nrf91_lte_monitor.c
Add symbol to control the log level of the LTE monitor handler in the common library. Quiet the log output by changing RRC log messages to DBG level and setting the default LTE Monitor log level to INF.
Resolves https://github.com/golioth/firmware-issue-tracker/issues/448
=> zephyr: common: add LTE handler log level symbol

src/rpc.c, tests/unit_tests/test_rpc.c
`NOT_FOUND` is a more intuitive error code for the case where the device receives an RPC call for a method that isn't registered with the SDK.
Resolves golioth/firmware-issue-tracker#466
=> rpc: return `NOT_FOUND` instead of `UNKNOWN`

tests/hil/tests/settings/test_settings.py
Add delay so slower devices have time to initialize NVS.
This resolves an issue I'm seeing with the nRF52840 where the credentials are not being stored because they are written before NVS is ready:
```
------------------------------------------------------------------------------------ Captured stdout setup ------------------------------------------------------------------------------------
o come up
uart:~$
uart:~$ settings set wifi/ssid "MySSID"
Setting wifi/ssid to MySSID
Failed to save setting wifi/ssid:MySSID
[00:00:02.707,366] <inf> wifi_esp_at: AT version: 2.4.0.0(s-4c6eb5e - ESP32 - May 20 2022 03:12:58)
[00:00:02.710,571] <inf> wifi_esp_at: SDK version: qa-test-v4.3.3-20220423
[00:00:02.716,979] <inf> wifi_esp_at: Bin version: 2.4.0(WROVER-32)
[00:00:03.159,454] <inf> …
```
=> hil: zephyr: add delay before provisioning

.github/workflows/hil_test_zephyr.yml
During a rebase conflict resolution, the line that sets the CoAP gateway URI override was accidentaly dropped.
=> ci: fix CoAP gateway override for Zephyr tests

.github/workflows/lint_build_unit_test.yml
Update `gdown` python package to latest to fix broken Google Drive download.
=> CI: modustoolbox: fix download from Google Drive

.github/workflows/hil_sample_zephyr.yml, .github/workflows/hil_test_zephyr.yml, .github/workflows/hil_tests.yml, examples/zephyr/hello/pytest/test_sample.py, examples/zephyr/lightdb/delete/pytest/test_sample.py, examples/zephyr/lightdb/get/pytest/test_sample.py, examples/zephyr/lightdb/observe/pytest/test_sample.py, examples/zephyr/lightdb/set/pytest/test_sample.py, examples/zephyr/settings/pytest/test_sample.py
Enable nRF9160dk CI testing with an erase step as the final (required) step of the workflow. This ensures that after a test a dev board will not continue to be connected to the cellular network, accruing data usage charges.
=> ci: erase nRF9160 at end of tests

tests/hil/scripts/pytest-hil/board.py, tests/hil/tests/settings/test_settings.py
Now that we erase the baords between test runs, we need to delay at the start of each test to give time for the settings partition to be reformatted before we attempt to store settings to flash.
This is a temporary fix until a more robust solution is in place.
=> tests: hil: connection: delay for NVS init at test start

examples/zephyr/common/settings_golioth.c
Limit the runtime settings input length for PSK-ID and PSK to match the Kconfig setting for those lengths.
Resolves https://github.com/golioth/firmware-issue-tracker/issues/451
=> zephyr: common: limit runtime PSK-ID / PSK length

examples/zephyr/hello/sample.yaml, examples/zephyr/lightdb/delete/sample.yaml, examples/zephyr/lightdb/get/sample.yaml, examples/zephyr/lightdb/observe/sample.yaml, examples/zephyr/lightdb/set/sample.yaml, examples/zephyr/lightdb_stream/sample.yaml, examples/zephyr/logging/sample.yaml, examples/zephyr/rpc/sample.yaml, examples/zephyr/settings/sample.yaml
The nrf9160 was sometimes hitting twister timeouts before it was able to establish a cell connection. This overall timeout was shorter than the sum of the individual timeouts in the pytest file. This timeout is a last case timeout to detect a hung board, not to ensure compliance with any deadline, so it doesn't need to be particularly tight. Extending it to 180 seconds should give plenty of time for the board to connect to the cell network and complete the test.
Fixes golioth/firmware-issue-tracker#479
=> examples: zephyr: extend twister test timeouts

examples/esp_idf/lightdb/set/pytest/test_sample.py
Pytest was querying the backend for the counter value before the device had successfully set the counter value. Now, the pytest script explicitly waits for the device to report the counter has been set before querying the backend for the value.
Fixes golioth/firmware-issue-tracker#478
=> examples: esp_idf: lightdb_set: wait for counter set message during test

examples/esp_idf/hello/main/app_main.c, examples/esp_idf/lightdb/observe/main/app_main.c, examples/esp_idf/rpc/main/app_main.c
Some examples posted to the connected semaphore immediately after creating it, which would cause the example to run immediately without waiting for the client to connect.
Fixes golioth/firmware-issue-tracker#477
=> examples: esp-idf: fix premature post to connected semaphore

tests/hil/tests/connection/test_connection.py, tests/hil/tests/settings/test_settings.py
Some boards (e.g. cellular connected boards) can take a long time to connect to the internet. Increase the timeout when waiting for a connection to accomodate these boards.
Fixes golioth/firmware-issue-tracker#480
=> tests: hil: increase connection timeout

src/coap_client_zephyr.c
Run the golioth_sys_client_disconnected() function when CoAP detects a disconnect event. This behavior is present in the libcoap support but was missing from the Zephyr coap support.
=> zephyr: coap: run golioth_sys_client_disconnected()

port/zephyr/golioth_log_zephyr.c
If the application activates the Golioth log backend before a connection to Golioth is in place, the backend context hasn't been set and checking members of the context will cause a crash.
- test for null context before checking context members
- format the code (I'm unsure how this file was missed during the giant code reformat PR awhile ago
=> Check backend context for null

.github/workflows/hil_sample_esp-idf.yml, .github/workflows/hil_test_esp-idf.yml, .github/workflows/test_esp32s3.yml
If a board had stored credentials when a test runs, the new credentials may not be used immediatel in some cases. For instance, if a WiFi-based board has already established a connection when new credentials are set, they will not be immediately used since a connetion is currently in place.
This commit erases board flash at the end of test runs to ensure all applications will be provisioned with the expected AP/Golioth device credentials the next time a test runs.
=> workflows: esp-idf: erase boards after tests

examples/zephyr/fw_update/pytest/test_sample.py
Monitor the fw_update CI testing to confirm reboot message at the end of the block download.
=> workflows: zephyr: watch for fw_update reboot

examples/esp_idf/rpc/pytest/test_sample.py
`test_logging()` should be `test_rpc()`
=> examples: esp-idf: rpc: fix incorrect name for pytest function

examples/esp_idf/rpc/main/app_main.c, examples/esp_idf/rpc/pytest/test_sample.py, src/rpc.c
Some failures in CI were caused by the test script attempting to call the RPC before the device had established an observation on the RPC endpoint. This commit adds a new message that the device prints when it has established the observation, and updates the test script to wait for that message.
Fixes golioth/firmware-issue-tracker#487
=> examples: esp-idf: rpc: wait for RPC registered before calling in test

examples/zephyr/certificate_provisioning/prj.conf
To use `log halt` and `log go`, CONFIG_LOG_CMDS must be selected.
This is expected behavior following [an upstream change](https://github.com/zephyrproject-rtos/zephyr/pull/65307).
Resolves https://github.com/golioth/firmware-issue-tracker/issues/486
=> zephyr: certificate_provisioning: enable log shell commands

.github/workflows/hil_sample_esp-idf.yml, .github/workflows/hil_sample_zephyr.yml, .github/workflows/hil_test_esp-idf.yml, .github/workflows/hil_test_zephyr.yml
CI testing for lightdb_stream began failing over the weekend after the Python trio package v0.25.0 was released. trio was locked to v0.24.0 in the golioth-python-tools package (v0.6.2) to avoid the errors.
=> ci: update golioth-python-tools to v0.6.2

src/zephyr_coap_req.c
The Zephyr CoAP stack filters out unknown CoAP codes, but due to a bug, it incorrectly filters out the TOO_MANY_REQUESTS message. We log an error when we receive an unknown code, which results in us getting into a loop where the server responds with TOO_MANY_REQUESTS, the device logs an error in response, and the loop repeats.
This bug is fixed in Zephyr upstream, but not in the latest release of NCS. To workaraound the issue in NCS, we can retrieve the code by directly indexing into the header, bypassing the filtering done by the Zephyr CoAP stack. When NCS is updated to include the fix, we will revert this change.
This issue is currently being experienced by a customer: https://forum.golioth.io/t/sdk-0-10-0-sends-15million-logs-day-in-error-condition/504/4
=> zephyr_coap_req: directly index into header for coap response code

.github/workflows/hil_sample_esp-idf.yml
Updates the HIL esp-idf samples workflow to set the CoAP URI in the sdkconfig.defaults file of each respective sample, rather than the HIL connection test.
=> ci: hil: set CoAP URI in correct sdkconfig.defaults files

.github/workflows/hil_sample_esp-idf.yml, .github/workflows/hil_sample_zephyr.yml, .github/workflows/hil_test_esp-idf.yml, .github/workflows/hil_test_zephyr.yml, .github/workflows/test_esp32s3.yml
- Update workflows to turn USB hub on at the start of a test and off at the end of it.
- Update docker images with USB hub control that uses parameters for on/off/cycle control.
resolves https://github.com/golioth/firmware-issue-tracker/issues/389
=> CI: power USB hub on before test and off afterward

.github/workflows/hil_test_linux.yml, .github/workflows/hil_tests.yml, tests/hil/platform/linux/CMakeLists.txt, tests/hil/platform/linux/README.md, tests/hil/platform/linux/golioth_user_config.h, tests/hil/platform/linux/main.c, tests/hil/scripts/pytest-hil/linuxboard.py, tests/hil/scripts/pytest-hil/plugin.py
This adds a Linux "board" target for our hil test framework, a Linux application base to run the test firmware, and a GH actions workflow to run these tests in CI. We'll use this target to gather code coverage numbers for our libcoap based ports.
Resolves golioth/firmware-issue-tracker#462
=> Linux hil tests

.github/workflows/hil_sample_zephyr.yml, examples/zephyr/certificate_provisioning/pytest/conftest.py
Zephyr 3.6 added support for passing pytest arguments via the command line when using Twister. This allows us to standardize the way we push arguments into the tests between Twister and our HIL tests.
=> ci: pass pytest args to twister via command line

.github/workflows/hil_sample_esp-idf.yml, .github/workflows/hil_sample_zephyr.yml, .github/workflows/hil_test_esp-idf.yml, .github/workflows/hil_test_linux.yml, .github/workflows/hil_test_zephyr.yml
Use the `--mask-secrets` option for the Golioth pytest plugin to mask generated PSK-ID/PSK secrets during GitHub Actions runs.
Fixes golioth/firmware-issue-tracker#507
=> ci: mask generated secrets in GitHub Actions logs

.github/workflows/test_esp32s3.yml
This is a legacy test and is locked to a specific runner. The physical board was moved to a different runner and this update matches the change.
=> workflows: move esp32s2 test to different runner

examples/zephyr/certificate_provisioning/pytest/conftest.py, examples/zephyr/fw_update/pytest/conftest.py, examples/zephyr/fw_update/pytest/test_sample.py, examples/zephyr/hello/pytest/conftest.py, examples/zephyr/hello/pytest/test_sample.py, examples/zephyr/lightdb/delete/pytest/conftest.py, examples/zephyr/lightdb/delete/pytest/test_sample.py, examples/zephyr/lightdb/get/pytest/conftest.py, examples/zephyr/lightdb/get/pytest/test_sample.py, examples/zephyr/lightdb/observe/pytest/conftest.py, examples/zephyr/lightdb/observe/pytest/test_sample.py, examples/zephyr/lightdb/set/pytest/conftest.py, examples/zephyr/lightdb/set/pytest/test_sample.py, examples/zephyr/lightdb_stream/pytest/conftest.py, examples/zephyr/lightdb_stream/pytest/test_sample.py, examples/zephyr/logging/pytest/conftest.py, examples/zephyr/logging/pytest/test_sample.py, examples/zephyr/rpc/pytest/conftest.py, examples/zephyr/rpc/pytest/test_sample.py, examples/zephyr/settings/pytest/conftest.py, examples/zephyr/settings/pytest/test_sample.py
Those args are not used by most targets, so make those optional and
configure WiFi credentials over Zephyr shell only when those were
passed.
=> examples: zephyr: pytest: make --wifi-{ssid,psk} pytest args optional

port/linux/golioth_sys_linux.c
There was a build warning `-Wimplicit-function-declaration` about missing
`#include <string.h>` statement in order to use `memcpy()`. Add that now.
While at it, sort all system header files alphabetically.
=> linux: add missing string.h header for memcpy()

src/coap_client_zephyr.c, tests/hil/tests/connection/test.c, tests/hil/tests/connection/test_connection.py
Monitor `client->run_sem` semaphore, similar to how libcoap implementation does.
=> coap_client: zephyr: handle connection stop

src/coap_client_zephyr.c
Add observations to the client struct when they are registered so that each observation may be reestablished when the client reconnects.
resolves https://github.com/golioth/firmware-issue-tracker/issues/525
=> zephyr: coap: reestablish observation after reconnect

tests/hil/tests/rpc/test.c, tests/hil/tests/rpc/test_rpc.py
Add a new case to the RPC HIL suite to test whether we reestablish observations after the client is disconnected.
These tests fail in this PR, but I ran a test on a branch on that includes @szczys's fix and those pass: https://github.com/golioth/golioth-firmware-sdk/actions/runs/8730075595
=> tests: hil: rpc: test re-establishment of observations

examples/zephyr/lightdb/set/pytest/test_sample.py
Wait for confirmation that the value has been set before fetching the value from the backend.
Resolves golioth/firmware-issue-tracker#548
=> examples: zephyr: lightdb/set: fix intermittent test failure

src/coap_client.c
Check if `path != NULL`, similar to how we check if `client != NULL`.
=> coap_client: check for 'path != NULL'

.github/workflows/hil_test_linux.yml, src/coap_client.c, tests/hil/tests/ota/test.c, tests/hil/tests/rpc/test.c, tests/hil/tests/settings/test.c
The HIL tests were not waiting for the client to be connected before establishing observations. See for example [this test run](https://github.com/golioth/golioth-firmware-sdk/actions/runs/8791389071/job/24128163197#step:6:547):
```
time: 1713828580.7902908 log: W (0) golioth_coap_client: Client not running, dropping observe request for path .rpc/
```
This could cause some tests to fail to establish an observation, which would cause the test to fail. To fix, the test waits on a semaphore that is posted by a callback that is executed upon client connection, the same way as the examples.
Also, improve the logging around failures to send requests while the client is disconnected by logging the full path (including prefix) and disambiguating between request type.
Fixes …
=> HIL: Wait for Client connection before establishing Observations

.github/workflows/hil_test_esp-idf.yml
This allows to stop CI pipeline early on build stage, instead of trying to execute those tests on HIL.
Example build failures:
- https://github.com/golioth/golioth-firmware-sdk/actions/runs/8799855533/job/24149764163?pr=460
- https://github.com/golioth/golioth-firmware-sdk/actions/runs/8799855533/job/24149763317?pr=460
- https://github.com/golioth/golioth-firmware-sdk/actions/runs/8799855533/job/24149763552?pr=460
=> ci: esp-idf: exit with error code in 'Build Test Firmware' job

.github/workflows/pre-commit.yml, .pre-commit-config.yaml
I had some issues using `pre-commit` locally w/ Python 3.12, e.g.
```
ERROR: Failed building wheel for python-Levenshtein-wheels
```
Auto-upgrading the pre-commit dependencies (`pre-commit autoupdate`) to their latest versions fixed these issues.
I also had to upgrade the `pre-commit` docker image to `kiwicom/pre-commit:3.6.0` due to https://github.com/Lucas-C/pre-commit-hooks/issues/83
=> pre-commit: Update pre-commit repo revisions

src/coap_client_zephyr.c, tests/hil/platform/zephyr/README.md, tests/hil/tests/ota/README.md, tests/hil/tests/rpc/README.md, tests/hil/tests/rpc/test_rpc.py
Observations are stored in the golioth client struct so that the data may be used to reestablish observations upon reconnect. When the Golioth client is stopped, all requests in the client->coap_reqs linked list are freed. This causes the client address in the stored observation to change, leading to a crash when trying to reestablish. This commit skips freeing observations so the data remains intact. This memory should only be freed when cancelling an observation.
resolves https://github.com/golioth/firmware-issue-tracker/issues/557
=> zephyr: coap: skip free for observations

tests/hil/tests/rpc/test_rpc.py
Seems that most ESP32 boards are registering RPC significantly slower
pytest testcases are invoked. As a result first testcase timeouts due to
ESP32 boards being not ready to handle RPCs.
Fix that race condition by introducing waiting "for RPC observation
established" log message, which is generated after RPC registration has
been acknowledged by Golioth backend.
=> tests: hil: rpc: wait for RPCs to be registered before running testcases

examples/zephyr/lightdb/observe/pytest/test_sample.py
Fixes regex to match the pipe character exactly by escaping it. Previously it was being interpreted as an OR operator in the regex.
=> hil: zephyr: lightdb: match pipe character exactly in regex

examples/zephyr/lightdb_stream/pytest/test_sample.py, examples/zephyr/lightdb_stream/src/main.c
Update the `lightdb_stream` example app to include sync & async examples showing how to send CBOR-encoded sensor data to LightDB Stream.
If you don't want the last commit (dc055c6464d0c34445f1a53275033b6e1dea2ca6) just LMK and I can drop it (was just trying to consolidate duplicate code)
=> examples: zephyr: Add CBOR examples to lightdb_stream example app

examples/zephyr/lightdb_stream/src/main.c
When a `temp0` devicetree alias is added to the board overlay, the `get_temperature` function was looping through all sensor channels, always returning the result of reading the last one, even if it was not a supported channel.
This fixes the function so that it returns after the first successful read from a temperature channel.
=> examples: zephyr: Fix get_temperature with temp0 DT alias

src/settings.c
If a resonse to a settings update is not sent back to the server, the device settings status will not be updated. This commit reports failure to send the response as a log message.
=> settings: check for error when responding to server

src/fw_update.c
Include the target firmware version when settings the UPDATING status on the server. This matches the behavior for the DOWNLOADING and DOWNLOADED statuses.
resolves https://github.com/golioth/firmware-issue-tracker/issues/567
=> ota: include target version when status is UPDATING

src/coap_client.c, src/coap_client.h, src/coap_client_libcoap.c, src/coap_client_libcoap.h, src/coap_client_zephyr.c, src/coap_client_zephyr.h, src/lightdb_state.c, src/ota.c, src/rpc.c, src/settings.c, src/zephyr_coap_req.c, src/zephyr_coap_req.h, tests/hil/platform/zephyr/README.md, tests/hil/tests/rpc/test.c, tests/hil/tests/rpc/test_rpc.py, tests/unit_tests/fakes/coap_client_fake.c, tests/unit_tests/fakes/coap_client_fake.h, tests/unit_tests/test_rpc.c
Add ability to remove observations from the client coap_reqs lists, and mark the observation slots as not in_use. The cancellation process sends an "eager release" coap packet to the server indicating the observation has been  cancelled.
This searches the coap_reqs linked list by matching the request message pointer which is why the `coap_client.h` header was included. I think a future improvement to how observations are handled should be storing crucial observation values instead of the the request message. If we store the coap token as one of those values, it can be used to search in the coap_reqs.
* This should be merged after #467
* This should be merged after #452
* resolves https://github.com/golioth/firmware-issue-tracker/issues/519
=> zephyr: coap: add cancel observations

tests/hil/tests/ota/test.c, tests/hil/tests/ota/test_ota.py
Adjust OTA test timing to reduce tests that fail due to propagation delay.
https://github.com/golioth/firmware-issue-tracker/issues/568
=> HIL: adjust OTA test timing

include/golioth/settings.h, src/settings.c, tests/hil/tests/settings/test.c, tests/hil/tests/settings/test_settings.py
Add API to cancel settings observations and free the settings service context.
Resolves https://github.com/golioth/firmware-issue-tracker/issues/521
=> Add settings cancel API

CHANGELOG.md, port/esp_idf/components/golioth_sdk/Kconfig, port/zephyr/Kconfig, src/Kconfig, src/Kconfig.authentication, src/Kconfig.coap, src/Kconfig.logging
Break Kconfig symbols out into files that group them by type. Update the Zephyr Kconfig to include the various new Kconfig groups into menus for better presentation in menuconfig.
resolves https://github.com/golioth/firmware-issue-tracker/issues/571
=> kconfig: re-organize Kconfig symbols for menuconfig

include/golioth/ota.h, src/ota.c
Add a public API to the OTA service for downloading a single component of a release. This uses the new blockwise transfer module under the hood (as opposed to the fw_block_processor module used by the fw_update module). Users can use this new API, along with existing APIs around OTA manifests, to implement their own firmware update mechanism, including implementing support for multi-artifact updates.
~NOTE: I haven't actually tested this yet, but throwing it up early for feedback on the API and approach.~
This is ready for review
=> ota: add `golioth_ota_download_component()` api

tests/hil/tests/rpc/test.c, tests/hil/tests/rpc/test_rpc.py
In the observation_repeat_restart test, we were waiting for the device to establish a connection to Golioth before the test script sends an RPC to the device. This creates a small window between when the device establishes a connection and when it establishes an observation on the RPC path where attempts to send an RPC will fail. Instead, we should wait for the device to report that is successfully established an observation before the test script attempts to send any RPCs to the device. This matches the behavior in other parts of the test script.
=> tests: hil: rpc: wait for RPC establishment before sending RPCs

tests/hil/tests/ota/test.c, tests/hil/tests/ota/test_ota.py
Previously, the test script was waiting on a string printed by the device _before_ it reports it status, then waiting for a specific delay before retrieiving the reported status from the backend. Instead, the test script now waits for a string that is printed by the device after it receives an acknowledgement from the server that the status update has been posted successfully. This makes the timing of the test more explicit and should reduce timing related failures in CI.
=> tests: hil: ota: wait for successful status report

README.md, examples/zephyr/README.md
Fixes up a few straggling LightDB Stream links.
Mirrors changes made in https://github.com/golioth/golioth-firmware-sdk/commit/900678a3f363055258c4946b3be9c5222dad5ea4
=> Update remaining LightDB Stream links

tests/hil/tests/ota/test_ota.py
We were seeing the nrf9160dk timeout during the initial connection on the OTA test with a timeout of 60 seconds. This increases that value to 120 seconds, which matches what the other integrations tests use.
=> hil: ota: increase initial timeout to 120s

.github/workflows/hil_sample_esp-idf.yml, .github/workflows/hil_test_esp-idf.yml, .github/workflows/hil_test_linux.yml, .github/workflows/hil_test_zephyr.yml
Runs all HIL tests, even if one fails, instead of exiting after the first failure.
A test run in CI where I forced the OTA test to fail is here: https://github.com/golioth/golioth-firmware-sdk/actions/runs/9354727595
Resolves golioth/firmware-issue-tracker#577
=> ci: don't fail fast

examples/esp_idf/lightdb/delete/pytest/test_sample.py, examples/esp_idf/lightdb/get/pytest/test_sample.py, examples/esp_idf/lightdb/observe/pytest/test_sample.py, examples/esp_idf/lightdb/set/pytest/test_sample.py, examples/esp_idf/settings/pytest/test_sample.py, examples/esp_idf/stream/pytest/test_sample.py, examples/zephyr/lightdb/delete/pytest/test_sample.py, examples/zephyr/lightdb/observe/pytest/test_sample.py, examples/zephyr/lightdb/set/pytest/test_sample.py, examples/zephyr/logging/pytest/test_sample.py, examples/zephyr/rpc/pytest/test_sample.py, examples/zephyr/settings/pytest/test_sample.py, examples/zephyr/stream/pytest/test_sample.py, tests/hil/tests/settings/test_settings.py
`trio.sleep()` will just wait in async I/O loop, instead of freezing whole Python process. It also
makes more sense to be consistent and always use async APIs when needed. While at it sort imports
alphabetically.
Device might report that value is already deleted, but that state might still not be reflected
immediately with REST APIs. Sleep 2s before checking value with REST API, so test passes after
successful value deletion in lightdb.
=> examples: use trio.sleep() and wait 2s in lightdb/delete

examples/zephyr/certificate_provisioning/pytest/test_sample.py
Get the project id from the project fixture in pytest instead of using a hardcoded value. This allows the test to run on prod or dev.
This was tested against dev and found to be working: https://github.com/golioth/golioth-firmware-sdk/actions/runs/9387861576
resolves https://github.com/golioth/firmware-issue-tracker/issues/561
=> Update certificate_provisioning test so it can run on both dev and prod

src/coap_blockwise.c
There's no need to store the retry count in the blockwise transfer context structure. We can store it locally on the stack, which is both more efficient and easier to read.
Not that we aren't using the retry count yet, but we will as part of error handling.
=> blockwise: remove retry_count from the context structure

src/coap_client_zephyr.c, src/coap_client_zephyr.h, src/zephyr_coap_req.c
Sum the number of coap request resends over a period of time and report as an INF log message. Change the existing resend message to DBG level so it is still available when that log level is selected via Kconfig.
I'm proposing this approach as an alternative to #500. We had originally discussed changing the log level of `zephyr_coap_req.c` in only the golioth log backend so the messages are reported in the terminal but not sent to the cloud. This has two disadvantages:
- Setting a runtime level for that backend felt a little bit convoluted as it needs to be done after the backend is initialized and we don't initialize until after we connect to Golioth
- When only a few resend messsages occur, they're pretty handy to have (even on remote logs).
This PR is a rather small resource change …
=> zephyr: coap: periodically report resend count

src/coap_client.c, src/event_group.c
- When creating an event group, check for memory allocation and semaphore creation errors. Free memory as needed and return NULL
- During sync calls, check event group and sempahore for NULL. Free memory as needed and return GOLIOTH_ERROR_MEM_ALLOC
resolves https://github.com/golioth/firmware-issue-tracker/issues/582
=> coap client: handle allocation errors with sync calls

src/zephyr_coap_req.c
When the devices has connectivity issues, the "cancel and free" request messages can flood the logs. Change the level for those messages from INF to DBG.
=> zephyr_coap_req: reduce log level for "cancel and free" message

examples/esp_idf/lightdb/delete/pytest/test_sample.py, examples/esp_idf/lightdb/set/pytest/test_sample.py, examples/zephyr/lightdb/delete/pytest/test_sample.py, examples/zephyr/lightdb/set/pytest/test_sample.py, examples/zephyr/rpc/pytest/test_sample.py
In case of RPC wait for "RPC observation established" message before proceeding with test. This
change is only for Zephyr, since there is already such logic implemented for ESP-IDF test script.
In case of lightdb, solve existing isues by retries with delays.
=> examples: improve test reliability

tests/hil/tests/ota/test_ota.py
Introduces a short wait (2 seconds) for firmware update state changes to propagate. State changes are not guaranteed to be immediately reflected for a device after an OK response is received.
In the future, this stop-gap solution should be replaced by either polling in this test or synchronous behavior on the server. Currently the on-device test is waiting 7s between state updates, so the wait in this test must remain less than to avoid missing a state update.
=> hil: ota: wait for firmware update state to propagate

include/golioth/stream.h, src/stream.c
Some applications may wish to send data through pipelines that is larger than what we can support in a single transaction. In these cases, we can use CoAP blockwise transfers to send large payloads in multiple transactions. This commit exposes a new API in the Stream service for enabling blockwise uploads of stream data.
=> stream: Add support for blockwise uploads of stream data

port/zephyr/Kconfig, src/coap_client_zephyr.c
- ensure keepalive timer is reset after callback
- reset keepalive timer whenever a response is received
- remove ping timer logic and Kconfig symbol
The ping timer was duplicating the keepalive timer functionality. The keepalive is used by the libcoap platforms so this change brings better parity.
resolves https://github.com/golioth/firmware-issue-tracker/issues/592
=> zephyr: coap: fix keepalive behavior

include/golioth/client.h, include/golioth/config.h, include/golioth/fw_update.h, include/golioth/golioth_debug.h, include/golioth/golioth_status.h, include/golioth/golioth_sys.h, include/golioth/lightdb_state.h, include/golioth/log.h, include/golioth/ota.h, include/golioth/payload_utils.h, include/golioth/rpc.h, include/golioth/settings.h, include/golioth/stream.h, include/golioth/zcbor_utils.h
By adding an extern "C" block to header files, we avoid linking problems when building C++ applications that come from name mangling since C++ supports function overloading.
=> Add extern “C” block to header files

src/zephyr_coap_req.c
When printing a pointer to a log message, the pointer should be cast to (void *) to avoid the following warning messages:
> <wrn> cbprintf_package: (unsigned) char * used for %p argument. It's
> recommended to cast it to void * because it may cause misbehavior in
> certain configurations.
The origin of the warning message is explained here: https://github.com/zephyrproject-rtos/zephyr/commit/a7224830ce865fd1ec6183093acf8d44a5659391
=> zephyr: coap: silence pointer warning in log messages

examples/common/golioth_basics.h, examples/esp_idf/common/sample_credentials.h, examples/esp_idf/common/util.h, examples/zephyr/common/include/samples/common/net_connect.h, examples/zephyr/common/include/samples/common/sample_credentials.h
Adds extern "C" declarations to headers to avoid name mangling when included in a C++ build.
> Note: some of the example headers already include `extern "C"` -- this just adds to those where is is missing.
=> examples: add extern C to headers

examples/zephyr/common/Kconfig.defconfig
Use the same logic, but implement it in more compact and readable way.
=> examples: zephyr: simplify EVENTFD_MAX default value

src/ota.c
hint that the GOLIOTH_OTA_MAX_NUM_COMPONENTS setting is the most likely cause of a manifest decoding error.
Message displays as follow:
resolves: https://github.com/golioth/firmware-issue-tracker/issues/612
=> ota: better error message on manifest decode error

port/freertos/golioth_sys_freertos.c, src/coap_client_libcoap.c, src/coap_client_zephyr.c, tests/hil/tests/connection/test.c, tests/hil/tests/connection/test_connection.py
- Fix memory free for post_block requests in both libcoap and Zephyr coap
- Stop client before destroying it in both libcoap and Zephyr coap
- libcoap: call golioth_sys_client_disconnected() when ending a session
- libcoap: disable automatic cloud logging when the client is disconnected
resolves https://github.com/golioth/firmware-issue-tracker/issues/584
=> Stop client before destroying

.github/workflows/hil_tests.yml
Adds the ability to select just one of the child HIL workflows to run when dispatching from the GitHub UI. This enables faster integration of HIL tests using fewer runner resources.
=> ci: add ability to choose workflow for HIL tests

examples/zephyr/certificate_provisioning/boards/nrf9160dk_nrf9160_ns.conf, examples/zephyr/fw_update/boards/nrf9160dk_nrf9160_ns.conf, examples/zephyr/golioth_basics/boards/nrf9160dk_nrf9160_ns.conf, examples/zephyr/hello/boards/nrf9160dk_nrf9160_ns.conf, examples/zephyr/hello_nrf91_offloaded/prj.conf, examples/zephyr/lightdb/delete/boards/nrf9160dk_nrf9160_ns.conf, examples/zephyr/lightdb/get/boards/nrf9160dk_nrf9160_ns.conf, examples/zephyr/lightdb/observe/boards/nrf9160dk_nrf9160_ns.conf, examples/zephyr/lightdb/set/boards/nrf9160dk_nrf9160_ns.conf, examples/zephyr/logging/boards/nrf9160dk_nrf9160_ns.conf, examples/zephyr/rpc/boards/nrf9160dk_nrf9160_ns.conf, examples/zephyr/settings/boards/nrf9160dk_nrf9160_ns.conf, examples/zephyr/stream/boards/nrf9160dk_nrf9160_ns.conf, port/zephyr/Kconfig
This is the minimal set of changes to enable support for the P-384 curve in the Zephyr based ports. We may wish to enable further curves and algorithms at a later date, but for now this immediately restores certificate functionality.
TODO:
Resolves golioth/firmware-issue-tracker#622
=> Enable p384 curve

examples/zephyr/certificate_provisioning/README.md, examples/zephyr/certificate_provisioning/pytest/test_sample.py, examples/zephyr/certificate_provisioning/sample.yaml, examples/zephyr/certificate_provisioning/src/main.c
This changes the certificate provisioning sample to repeatedly check for the presence of PKI credentials in the filesystem, instead of just once at boot as it previously did. This allows users (and more importantly, CI) to run through the example without needing to reset the board. Board that use a virtual COM port over a USB peripheral (like the RAK5010) will drop their serial connection if they reboot, so this change is necessary in order to test this sample in CI on those boards. Note that the certificate provisioning test will continue to fail until #554 is merged, but a passing run with the changes from that PR and the changes in this one can be found [here](https://github.com/golioth/golioth-firmware-sdk/actions/runs/10293915260/job/28491326370#step:8:49).
Resolves …
=> No reset in cert provisioning sample

include/golioth/client.h
Fixes broken links to device API documentation. The substructure of the device API docs may change in the future, so we opt to link to the index, which is unlikely to be moved.
=> docs: fix link to device API documentation

.github/workflows/hil_tests.yml
This adds the esp32 to twister tests with the following caveats:
- Starting with Zephyr v3.7.0 the fw_update test will target the blueprint `esp32_devkitc_wrover_esp32_procpu`. This is already set up on the server, along with an artifact (based on v0.14.0 of Golioth). New artifacts beginning with v0.15.0 must be uploaded using this blueprint name
- Many of these test will fail due to a issue with writing to flash on these devices. This issue is being worked on.
resolves https://github.com/golioth/firmware-issue-tracker/issues/336
=> hil: zephyr: include esp32_devkitc_wrover in twister testing

CHANGELOG.md, examples/zephyr/fw_update/boards/mimxrt1024_evk.overlay, examples/zephyr/golioth_basics/boards/mimxrt1024_evk.overlay, examples/zephyr/hello/boards/mimxrt1024_evk.overlay, examples/zephyr/lightdb/delete/boards/mimxrt1024_evk.overlay, examples/zephyr/lightdb/get/boards/mimxrt1024_evk.overlay, examples/zephyr/lightdb/observe/boards/mimxrt1024_evk.overlay, examples/zephyr/lightdb/set/boards/mimxrt1024_evk.overlay, examples/zephyr/logging/boards/mimxrt1024_evk.overlay, examples/zephyr/rpc/boards/mimxrt1024_evk.overlay, examples/zephyr/settings/boards/mimxrt1024_evk.overlay, examples/zephyr/stream/boards/mimxrt1024_evk.overlay
Zephyr v3.7.0 moves to NXP Ethernet driver which was exhibiting Link Down/Up behavior during OTA Firmware Update that resulted in the inability to download new firmware. This behavior is similar to issues reported upstream:
- https://github.com/zephyrproject-rtos/zephyr/issues/76446
- https://github.com/zephyrproject-rtos/zephyr/issues/76965
Cherry-picking the suggested patch did not resolve the issue. This commit reverts to the old driver using an overlay file for the mimxrt1024_evk. When there is an upstream fix available, these overlay files may be removed (note the certificate_provisioning example still needs the stab node in its board overlay file).
resolves https://github.com/golioth/firmware-issue-tracker/issues/642
=> zephyr: revert NXP Ethernet driver

CHANGELOG.md
Updates CHANGELOG.md with known issue when using the esp_at WiFi driver with certificate auth in Zephyr 3.7.
=> CHANGELOG: add known issue with esp_at driver

port/esp_idf/fw_update_esp_idf.c, port/esp_idf/golioth_port_config.h, port/linux/fw_update_linux.c, port/linux/golioth_sys_linux.c, port/zephyr/golioth_fw_zephyr.c, port/zephyr/golioth_log_zephyr.h, port/zephyr/golioth_sys_zephyr.c
Run clang-format on esp-idf, linux, and Zephyr .c and .h files.
=> Format port files

port/zephyr/include/golioth_port_config.h
Updates zephyr port config to only define the GLTH_LOGX macros if CONFIG_GOLIOTH_DEBUG_LOG is defined. Previously, a large number of redefinition warnings would be reported by the compiler due to definition of GLTH_LOGX macros to empty by the default system config when CONFIG_GOLIOTH_DEBUG_LOG=n.
Before this change when `CONFIG_GOLIOTH_DEBUG_LOG=n` in any Zephyr builds:
```
In file included from /home/hasheddan/code/github.com/golioth/customer-support/esp-at-zephyr-3.7/modules/lib/golioth-firmware-sdk/port/zephyr/../../include/golioth/config.h:24,
from /home/hasheddan/code/github.com/golioth/customer-support/esp-at-zephyr-3.7/modules/lib/golioth-firmware-sdk/port/zephyr/../../include/golioth/golioth_debug.h:14,
from /home/hasheddan/code/github.com/golioth/customer-support/esp-at-zephyr-3.7 …
```
=> port: zephyr: honor CONFIG_GOLIOTH_DEBUG_LOG

src/settings.c
When the settings observation handler runs, first check the response status and log/return errors if necessary before trying to process a payload.
resolves https://github.com/golioth/firmware-issue-tracker/issues/639
=> settings: check for server error in settings callback

include/golioth/golioth_sys.h, port/freertos/golioth_sys_freertos.c, port/linux/golioth_sys_linux.c, port/zephyr/golioth_sys_zephyr.c
- Add mutex API
- Implement mutex in esp-idf, linux, zephyr
edit: I retargeted this onto #565 so that auto-formating is contained to its own PR and not show in this or subsequent work.
resolves https://github.com/golioth/firmware-issue-tracker/issues/631
=> Add mutex API

examples/zephyr/fw_update/README.md, examples/zephyr/fw_update/pytest/README.md, examples/zephyr/fw_update/sample.yaml, examples/zephyr/golioth_basics/README.md
With NCS 2.7.0 comes support for 'sysbuild'. Use it, so there is the same
behavior with vanilla Zephyr and NCS.
=> examples: zephyr: use 'sysbuild' with NCS

.github/workflows/hil_tests.yml
By default, the esp32 west runner looks in the espressif HAL for the esptool.py script. Because we don't want to checkout the HAL during twister runs in CI (to save time), instead specify the path for esptool.py so that the runner will use the version installed from pip in the Docker container.
Resolves golioth/firmware-issue-tracker#652
=> ci: use esptool.py from pip instead of hal_espressif

.github/workflows/hil_test_linux.yml, .github/workflows/hil_tests.yml
Pass coverage data (twister generated coverage.json files) using artifacts.
Since there are multiple of those already (for 32 and 64 bit native_sim
variants) merge them in another job. Report coverage data in the job
summary GitHub Actions page. Additionally create a comment in PR using
XML (Cobertura) generated report.
=> ci: native_sim: generate coverage

tests/hil/platform/zephyr/src/main.c
This suppressses warning about missing return statement from non-void
function.
=> tests: hil: zephyr: return 0 from main()

tests/hil/scripts/pytest-hil/board.py, tests/hil/scripts/pytest-hil/espidfboard.py, tests/hil/scripts/pytest-hil/linuxboard.py, tests/hil/scripts/pytest-hil/ncsboard.py, tests/hil/scripts/pytest-hil/plugin.py, tests/hil/scripts/pytest-hil/pyproject.toml, tests/hil/scripts/pytest-hil/zephyrboard.py, tests/hil/tests/connection/test_connection.py, tests/hil/tests/lightdb/test_lightdb.py, tests/hil/tests/ota/test_ota.py, tests/hil/tests/rpc/test_rpc.py, tests/hil/tests/settings/test_settings.py, tests/hil/tests/stream/test_stream.py
Use `trio.run_process` to handle subprocess communication with
Linux (virtual) board. This simplifies receiving logic and handling
timeouts. Additionally it gives easier control over sending data to the
target (which was very difficult or impossible with
`subprocess.Popen.communicate()` API).
Use `trio-serial` for non-virtual (real hardware) boards, so the same
API and benefit as `trio.run_process()` gives is utilized for communicating
with them.
Share single `wait_for_regex_in_line()` implementation and just provide
target-specific (serial vs process) `receive_some()` API.
=> tests: hil: use async to communicate with HIL

examples/esp_idf/fw_update/pytest/test_sample.py, examples/esp_idf/hello/pytest/test_sample.py, examples/esp_idf/lightdb/delete/pytest/test_sample.py, examples/esp_idf/lightdb/get/pytest/test_sample.py, examples/esp_idf/lightdb/observe/pytest/test_sample.py, examples/esp_idf/lightdb/set/pytest/test_sample.py, examples/esp_idf/rpc/pytest/test_sample.py, examples/esp_idf/settings/pytest/test_sample.py, examples/esp_idf/stream/pytest/test_sample.py
This fixes commit 4aa8eb0ff883 ("tests: hil: use async to communicate with
HIL"), which converted some APIs to coroutines.
Fixes: 4aa8eb0ff883 ("tests: hil: use async to communicate with HIL")
=> examples: esp_idf: await for coroutines

.github/workflows/hil_test_esp-idf.yml, .github/workflows/hil_test_linux.yml, .github/workflows/hil_test_zephyr.yml, .github/workflows/hil_tests.yml, tests/hil/scripts/pytest-hil/plugin.py, tests/hil/scripts/pytest-hil/pyproject.toml
- Add Allure report fixtures to the pytest plugin used for our HIL integration testing
- Add pytest options to generate Allure report on each HIL integration workflow
- Gather reports from all workflows into a single archive. This archive uses the normal retention policy, while the individual files uses a 1 day retention as they are also present in  the single archive.
- If the board fixture fails, all subsequent test cases will not be categorized by the board-name but instead be shown in Allure as the generic path to the test directory. I've opened [a separate ticket](https://github.com/golioth/firmware-issue-tracker/issues/665) to track this issue.
resolves https://github.com/golioth/firmware-issue-tracker/issues/580
=> Add Allure reports to hil integration tests

.github/workflows/hil_sample_zephyr.yml, .github/workflows/hil_tests.yml, examples/zephyr/certificate_provisioning/pytest/conftest.py, examples/zephyr/fw_update/pytest/conftest.py, examples/zephyr/hello/pytest/conftest.py, examples/zephyr/hello_nrf91_offloaded/pytest/conftest.py, examples/zephyr/lightdb/delete/pytest/conftest.py, examples/zephyr/lightdb/get/pytest/conftest.py, examples/zephyr/lightdb/observe/pytest/conftest.py, examples/zephyr/lightdb/set/pytest/conftest.py, examples/zephyr/logging/pytest/conftest.py, examples/zephyr/rpc/pytest/conftest.py, examples/zephyr/settings/pytest/conftest.py, examples/zephyr/stream/pytest/conftest.py, tests/hil/scripts/pytest-zephyr-samples/plugin.py, tests/hil/scripts/pytest-zephyr-samples/pyproject.toml
This plug allows common options like WiFi credentials to be added to pytest from a central location rather than doing so in  every sample's contest.py file.
This plugin will be extended to add Allure reports to the samples in an upcoming PR.
=> Add pytest-zephyr-samples plugin

.github/workflows/hil_sample_zephyr.yml, .github/workflows/hil_tests.yml, tests/hil/scripts/pytest-zephyr-samples/plugin.py, tests/hil/scripts/pytest-zephyr-samples/pyproject.toml
Add Allure reports fixture to the pytest-zephyr-samples plugin so that reports are generated for all Twister tests.
#592 adds a workflow job that gathers individual reports from each job. That  will also gather these Zephyr sample reports once it and this PR are on main.
Depends on #593 
Resolved  https://github.com/golioth/firmware-issue-tracker/issues/660
=> Add Allure reports to Zephyr twister tests

.github/workflows/hil_sample_esp-idf.yml
- Add pytest options for allure reports to ESP-IDF samples workflow.
- This uses the allure fixtures already available in the pytest-hil plugin
resolves https://github.com/golioth/firmware-issue-tracker/issues/661
=> hil: esp-idf: samples: add allure reports

.github/workflows/hil_sample_zephyr.yml, .github/workflows/hil_tests.yml
Collect the suite report from each Twister run and use it to render a pass/fail grid in the checks tab of the PR.
Summaries of the integration tests will be added in an upcoming PR.
Depends on: [szczys/mask-workflow-secrets](https://github.com/golioth/golioth-firmware-sdk/pull/597)
Resolves https://github.com/golioth/firmware-issue-tracker/issues/662
=> workflows: add summary of Twister CI tests

.github/workflows/hil_sample_esp-idf.yml, .github/workflows/hil_sample_zephyr.yml, .github/workflows/hil_test_esp-idf.yml, .github/workflows/hil_test_zephyr.yml
A timeout will ensure that a hung test does prevent other tests that need to use self-hosted runners from running.
=> ci: add timeout for self-hosted runners

.github/workflows/hil_sample_zephyr.yml
By default, Twister marks tests that fail to build due to being out of ROM or RAM as "skipped" instead of "failed". This option was previously enabled for the deprecated "twister-build" workflow in 963df80 but we missed it when creating the current HIL workflow.
This also updates the workflow to run Twister tests even if some of them failed to build. This way, we can get as much information as possible. In particular, for the moment, this allows us to run Twister for ESP32_DevKitC_WROVER on most of the examples while the certificate examples remain broken due to bugs in Zephyr that prevent us from using either the second internal RAM bank or the external SPIRAM.
=> ci: catch ram/rom overflow build errors

.github/workflows/hil_sample_esp-idf.yml, .github/workflows/hil_sample_zephyr.yml, .github/workflows/hil_test_esp-idf.yml, .github/workflows/hil_test_linux.yml, .github/workflows/hil_test_zephyr.yml, .github/workflows/hil_tests.yml
Update all workflows to use safe-upload-artifacts whenever upload artifacts that may contain secrets.
- Binary artifact uploads from build steps do not contain secrets and still use upload-artifact directly
- The merge reports workflows combine artifacts that have already been uploaded (and therefor have already run through the safe upload)
- Remove a few erroneous ids and retention settings
resolves https://github.com/golioth/firmware-issue-tracker/issues/672
=> workflows: use safe-upload-artifacts throughout

.github/workflows/hil_sample_zephyr.yml
Using `always()` prevented workflows from being cancelled.
=> ci: use `!cancelled()` instead of `always()`

.github/workflows/hil_tests.yml, .github/workflows/reports-allure-publish.yml, tests/hil/scripts/pytest-zephyr-samples/plugin.py
add a workflow to gather all individual reports, publish them as an artifact, generate the Allure webpage, and save it to the `gh-pages` branch for automatic publishing to GitHub pages.
resolves https://github.com/golioth/firmware-issue-tracker/issues/663
=> Publish Allure reports to GitHub pages

src/coap_client_zephyr.c
The coap_client_zephyr.c file registers for logging but it does not pass a log level. This meant that enabling debug logging for the Golioth Firmware SDK did not include enabling logs from the zephyr client. This commit adds GOLIOTH_DEBUG_DEFAULT_LOG_LEVEL as the default log level.
resolves https://github.com/golioth/firmware-issue-tracker/issues/598
=> coap: zephyr: add log level zephyr coap client

.github/workflows/hil_tests.yml
This generates HTML coverage from all native_sim runs:
* both 32-bit and 64-bit
* samples and tests
Echo HIL and Twister gcovr tracefiles, which helps with visibility of what is actually combined to single gcovr output.
Drop HTML coverage generation from specific native_sim jobs, as that just shows partial result.
=> ci: coverage: generate HTML coverage

src/zephyr_coap_req.c
A workaround for the TOO_MANY_REQUESTS coap error code was put in place with 503456d because the upsteam fix was not yet included in NCS. Now that we have moved to NCS v2.7.0 this fix is in place and the workaround has been removed in favor of the coap_header_get_code() function.
Resolves https://github.com/golioth/firmware-issue-tracker/issues/646
=> coap: zephyr: replace workaround with coap_header_get_code()

tests/hil/scripts/pytest-hil/plugin.py, tests/hil/scripts/pytest-zephyr-samples/plugin.py
Use a setup wrapper in both pytest-hil and pytest-zephyr-samples plugins to ensure that Allure values (suite, tag, params, etc) are in place before any other setup happens for each test.
This solves an issue where tests that failed during the board fixture would not be categorized with other tests from the same suite when using Allure reports.
Resolves https://github.com/golioth/firmware-issue-tracker/issues/677
=> pytest: plugins: use setup wrapper to set Allure values

.github/workflows/reports-summary-publish.yml
Show the test-reporting summary information on the workflow summary page. This resolves the issue where the report appeared under random jobs when displaying on the checks page.
Resolves https://github.com/golioth/firmware-issue-tracker/issues/678
=> workflows: show outcome report on summary page

.github/workflows/reports-allure-publish.yml
Use forked version of allure-report-action that fixes the GitHub run URL when hosted on a different repo from the tests.
I opened a PR with these changes on the upstream repo: https://github.com/simple-elf/allure-report-action/pull/57
Once merged I will update to the new release.
Resolves https://github.com/golioth/firmware-issue-tracker/issues/675
=> workflows: use forked allure-report-action

examples/zephyr/rpc/pytest/test_sample.py
The RPC sample test function was `test_logging` which made disambiguating the results for the RPC test from the results for the logging test difficult.
=> examples: zephyr: rpc: fix typo in test name

.github/workflows/hil_test_linux.yml, .github/workflows/lint_build_unit_test.yml
Use number of detected system cores instead of always using 8 threads for
build using make.
=> ci: use nproc to determine number of CPU cores for make

tests/unit_tests/CMakeLists.txt
Seems that:
``` cmake
set(ENABLE_DOCS OFF)
```
is not respected. Convert that to:
``` cmake
option(ENABLE_DOCS "" OFF)
```
=> tests: unit: enforce ENABLE_DOCS=OFF by defining option()

.github/workflows/hil_sample_esp-idf.yml, .github/workflows/hil_test_esp-idf.yml, .github/workflows/hil_test_linux.yml, .github/workflows/hil_test_zephyr.yml, .github/workflows/hil_tests.yml, .github/workflows/pre-commit.yml
Use $(...) syntax, as it is more visually clear, simplifies nested quoting
and command substitution. See [1].
[1] https://mywiki.wooledge.org/BashFAQ/082
=> ci: convert backtick `...` to braces $(...) for command substitution

src/rpc.c
Use `int` when printing with `%.*` specifier (truncated string).
This suppresses following warnings:
```
warning: field precision specifier ‘.*’ expects argument of type ‘int’, but argument 2 has type ‘size_t’ ***aka ‘long unsigned int’*** [-Wformat=]
```
=> rpc: fix -Wformat warnings

src/coap_client.c
Use `%zu` for printing `size_t` types.
This suppresses following warnings:
```
warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
```
=> coap_client: fix -Wformat warnings

.github/workflows/hil_sample_esp-idf.yml, tests/hil/scripts/pytest-hil/plugin.py
ESP-IDF uses the pytest-hil plugin for both integration tests and sample tests. Add an optional --custom-suitename flag so the sample test gets a different suite name than the default "hil." name assigned by the plugin to all integration tests.
resolves https://github.com/golioth/firmware-issue-tracker/issues/680
=> HIL: fix espif sample suite name

.github/workflows/hil_test_linux.yml, .github/workflows/hil_tests.yml
Zephyr tests and samples coverage is handled using gcovr. Switch to that
tool for Linux tests as well for improved consistency. This also allows to
combine coverage results for Linux and Zephyr.
Use gcovr tool to generate JSON output for each test and put most of the
coverage report generation inside 'coverage' job:
* HTML report (instead of lcov -> genhtml in case of Linux)
* single PR comment from XML output (instead of having two comments, each
with slightly different format)
* GH Actions step summary that includes Linux platform coverage (which was
not generated before for Linux)
=> ci: linux: switch from lcov to gcovr

.github/workflows/hil_tests.yml
So far bash 'for' loop was used to iterate through all tests, then build
them, run pytest and capture coverage. This produced massive amount of logs
and as a result was very hard to find a problem when such occurred.
Add job (`hil_test_zephyr_nsim_matrix`) that dynamically generates matrix
based on the list of tests to execute. Then use matrix strategy to build
those tests, run pytest and capture coverage.
Split building, runtime execution and coverage capture into separate steps,
so that it improves:
* visual feedback in GitHub Actions UI when investigating failed jobs
* no `$EXIT_CODE` handling
* faster execution of "Re-run failed jobs" when only single test on a
single platform has failed (it makes it more likely to pass)
=> ci: zephyr: execute HIL tests in matrix jobs

port/zephyr/golioth_log_zephyr.c
Fix an off-by-one error when writing a null terminator to the end of a log message buffer before sending to Golioth.
When a log message is longer than the setting for the  maximum Golioth backend log buffer (CONFIG_LOG_BACKEND_GOLIOTH_MAX_LOG_STRING_SIZE), the message is truncated by writing a null terminator onto the end of the buffer. The index for this null terminator was using a counter that had already been incremented past the end of the buffer array. Instead, use a MIN() test to use either the counter value, or the final member of the buffer array.
=> zephyr: logging: fix off-by-one in log message length limit

src/coap_client_zephyr.c
Support for setting DTLS 1.2 Connection IDs was inadvertently removed in the transition from using libcoap with Zephyr to using the Zephyr CoAP client. This re-enables Connection ID support when CONFIG_GOLIOTH_USE_CONNECTION_ID is set. It is off by default.
See previous support added in https://github.com/golioth/golioth-firmware-sdk/pull/163
=> coap: zephyr: honor CONFIG_GOLIOTH_USE_CONNECTION_ID

.github/workflows/hil_tests.yml, .github/workflows/lint_build.yml, .github/workflows/lint_build_unit_test.yml
`tests/unit_tests/test.sh` is very verbose, while it is possible to do most
of it with single `ctest` command.
Use *Ninja* generator to build using multiple threads automatically.
Install both `gcovr` and `ninja` from pypi, so a single tool (pip) is used.
Move `unit_tests` job from `lint_build_unit_test.yml` to `hil_tests.yml`,
so that coverage data can be easily combined as part of single workflow.
Also rename `lint_build_unit_test.yml` to `lint_build.yml`, as there are no
more unit tests as part of this workflow.
=> ci: unit_tests: merge coverage with HIL tests

.github/workflows/hil_sample_esp-idf.yml, .github/workflows/hil_sample_zephyr.yml, .github/workflows/hil_test_esp-idf.yml, .github/workflows/hil_test_linux.yml, .github/workflows/hil_test_zephyr.yml, .github/workflows/tests.yml
Install dependencies using single invocation to 'pip', so that:
* Python interpreter is loaded once
* dependencies resolution is calculated once
This saves about 15% of execution time (9.5s -> 8s on Ryzen 5950X).
=> ci: hil: prefer single-line pip invocations

.github/workflows/hil_sample_zephyr.yml
Comma after board label is causing tests to not be able to find runners.
=> workflows: zephyr: remove extra comma from runs-on entry

.github/workflows/hil_sample_esp-idf.yml, .github/workflows/hil_sample_zephyr.yml, .github/workflows/hil_test_esp-idf.yml, .github/workflows/hil_test_zephyr.yml, .github/workflows/tests.yml
- Update all workflows to use the latest images
- Update all instances of the Zephyr toolchain to 0.16.8 to match the latest images
Resolves https://github.com/golioth/firmware-issue-tracker/issues/667
=> workflows: update to latest images and Zephyr 0.16.8

src/coap_client_libcoap.c
When performing a block upload, honor requests from the server for  a smaller block size.
Resolves: https://github.com/golioth/firmware-issue-tracker/issues/670
=> libcoap: block-upload: allow server-negotiated block size

CHANGELOG.md, include/golioth/ota.h, src/coap_blockwise.c, src/coap_blockwise.h, src/fw_update.c, src/ota.c
Block download callbacks now receive both block_size and current_block_len. These distinct values are needed to correctly calculate the offset when the final block is received and its data payload (current_data_len) is smaller than the coap blocksize (block_size).
Resolves https://github.com/golioth/firmware-issue-tracker/issues/656
=> Block download: add current_block_len

src/coap_blockwise.c, src/coap_blockwise.h, src/stream.c
`golioth_blockwise_post()` was just returning `enum golioth_status`. Add
support for `set_cb`, which will be called in case of response to blockwise
POST request.
=> coap_blockwise: support passing set_cb to golioth_blockwise_post()

.github/workflows/reports-allure-publish.yml
- Use separate subdirectories for building Allure reports on `main` from those built on all other branches.
- Copy the index.html for the main branch to root so the landing page always shows the latest `main` branch reports
- Update the summary link to include the subdirectory
Resolves https://github.com/golioth/firmware-issue-tracker/issues/664
=> workflows: allure: separate main branch from others

.github/workflows/reports-allure-publish.yml
a space in the line continuation is causing the index.html copy step to fail because the os sees the destination directory name as beginning with a space.
=> workflows: allure-report: fix space in line continuation

CHANGELOG.md, include/golioth/ota.h, src/coap_blockwise.c, src/coap_blockwise.h, src/fw_update.c, src/ota.c
Add `golioth_ota_download_component_resumable()` that takes a block_idx to start the download and returns the next expected block_idx which may be used to resume when a block download fails before the final block.
Resolves https://github.com/golioth/firmware-issue-tracker/issues/684
Resolves https://github.com/golioth/firmware-issue-tracker/issues/686
=> OTA: add function for resuming component download

include/golioth/golioth_status.h, src/coap_blockwise.c
Add error handling to the blockwise upload operation.
- Propagate any error returned by the application write block callback back to the initial call.
- Add an error condition for invalid block size and check the block size returned by the application callback for bounding.
- Check the status and response at the end of a block-write operation and only call the set_cb callback if there was no local error (it should still be called for successful block upload, and errors returned from the server during coap operations).
Resolves https://github.com/golioth/firmware-issue-tracker/issues/712
This implements the parts of an existing PR that are still relevant to the current state of the SDK so this PR also:
- Closes #489
=> Blockwise upload error handling

src/coap_blockwise.c
Propagate any errors from the user callback out to the initial blockwise download call.
Resolves https://github.com/golioth/firmware-issue-tracker/issues/713
This implements the parts of an existing PR that are still relevant to the current state of the SDK so this PR also:
- Closes #491
=> Blockwise download error handling

examples/zephyr/fw_update/sample.yaml
Use `rak5010/nrf52840` instead.
=> examples: zephyr: fw_update: fix rak5010 board name in sample.yaml

examples/zephyr/certificate_provisioning/pytest/conftest.py, examples/zephyr/certificate_provisioning/pytest/test_sample.py
- drop spaces around `=` to suppress flake8's "unexpected spaces around keyword / parameter equals"
warning
- use build directory as CWD, so that certs/keys are stored in per-application directory (instead of
current directory from which twister is invoked)
- use twister serial for mcumgr, so `--device-port` CLI argument (or `CI_DEVNAME_PORT` environment
variable) is not required
=> examples: zephyr: certificate_provisioning: pytest improvements

tests/hil/tests/ota/test.c, tests/hil/tests/ota/test_ota.py
Use 1 Hz polling in pytest to catch reason and state changes more efficiently.
This removes an arbitrary delay, instead trying multiple times to get the device's reported reason and state codes. On the final timeout, the asserts will always be run so we retain helpful logging messages. This PR also reduces the device delay by 3 seconds, which equates to 30 seconds saved across all reason codes.
=> hil: ota: use 1 Hz polling for reason and state test

examples/zephyr/certificate_provisioning/pytest/test_sample.py
Rename the pytest function used to test the certificate provisioning sample from `test_credentials()` to `test_cert_provisioning()`. This will make it easier to identify the test in Allure reports.
=> examples: zephyr: rename certificate provisioning test func

.github/workflows/tests.yml
Jobs set to !cancelled() were still running when steps they depend on where skipped. In the case of Zephyr sample summaries for nsim, integration tests were failing because these summary steps still ran even though the summary tests were skipped.
Use success() || failure() to only run when the job either failed or succeeded.
Zephyr Sample summary steps running during unrelated integration jobs
=> hil: tests: use success/failure instead of cancelled

examples/linux/certificate_auth/README.md, examples/linux/certificate_auth/main.c
Switches to using int as return type for read_file to properly detect
errors.
Signed-off-by: Daniel Mangum <georgedanielmangum@gmail.com>
Updates to generate PEM device certificates, which are expected by the
certificate_auth sample application.
Signed-off-by: Daniel Mangum <georgedanielmangum@gmail.com>
Updates the README.md to instruct the user to obtain the root CA
certificate from the SDK source.
Signed-off-by: Daniel Mangum <georgedanielmangum@gmail.com>
=> examples: linux: fix error checks and update information to match current cert usage

examples/linux/certificate_auth/main.c
If multiple CA certificates are included in the PEM file it could easily overflow the 2048 limit. This doubles the max to provide plenty of space for 2 certificates, which is the common case.
=> examples: linux: increase max size of CA cert PEM file

.github/workflows/tests.yml
The `secrets_json` argument is used with the `safe-upload-artifacts` action, and is not a valid argument to the standard `upload-artifacts` action. Coverage information does not contain sensitive information so we can continue using the standard upload action. Remove the unused argument to suppress warnings in the GitHub Actions UI.
This is the warning in question:
=> ci: remove unused arg from coverage upload

examples/zephyr/fw_update/pytest/test_sample.py
Use information provided by 'fw_info' fixture to obtain artifact package
and version.
=> examples: zephyr: fw_update: deduplicate hardcoded package and version

tests/hil/scripts/pytest-zephyr-samples/plugin.py
Fallback to device serial when both `--hil-board` and `${hil_board}` are
missing. This allows to successfully run twister without providing those.
This also fixes parallel run of twister for many platforms, which requires
each to be unique in that scenario.
=> tests: hil: make --hil-board and ${hil_board} optional

CHANGELOG.md, examples/modus_toolbox/golioth_basics/golioth_app/Makefile, include/golioth/golioth_sys.h, include/golioth/ota.h, port/esp_idf/components/golioth_sdk/CMakeLists.txt, port/freertos/golioth_sys_freertos.c, port/linux/golioth_sdk/CMakeLists.txt, port/linux/golioth_sys_linux.c, port/utils/hex.c, port/utils/hex.h, port/zephyr/golioth_sys_zephyr.c, src/ota.c, tests/hil/tests/ota/test.c
Add an API for generating a sha256 hash that can be used to validate an OTA component.
Resolves https://github.com/golioth/firmware-issue-tracker/issues/717
=> port: add sha256 API

tests/hil/tests/ota/test.c, tests/hil/tests/ota/test_ota.py
- Add HIL test for resuming component download and verifying the hash
I had considered replacing the block download part of the test_block_ops() function, but that uses a non-callback approach to fetching the blocks so I thought it would be best to have both approaches tested.
Resolves https://github.com/golioth/firmware-issue-tracker/issues/44
Resolves https://github.com/golioth/firmware-issue-tracker/issues/716
=> Component Download: implement HIL test for resuming download and verifying component hash

.ci-west-ncs-twister.yml, .ci-west-ncs.yml, .github/workflows/hil_sample_zephyr.yml, west-ncs.yml
So far twister build stage was run either with Zephyr or NCS fork of
Zephyr. Twister test stage was run always with Zephyr.
This approach is not compatible anymore (since there are obviously two
different twister implementations) after switching to Zephyr 4.0.0 and NCS
2.8.0.
Introduce `.ci-west-ncs-twister.yml` and allow `nrf` and `zephyr` repositories
to make tests work with twister. Use it to initialize SDK with NCS and NCS' fork
of Zephyr as dependencies, so that the same twister implementation is used for
build and testing.
Fixes: 7aa069cdc22f ("bump NCS to 2.8.0")
=> ci: run twister tests using with NCS when using nrf9160dk

examples/zephyr/common/Kconfig
Using a PSK that is longer than 32 bytes does not work because the default MBEDTLS_PSK_MAX_LEN is set to 32 bytes. In the event that MBEDTLS_BUILTIN is set, the default will be 32. However, if MBEDTLS_BUILTIN is not set, as is the case when NRF_SECURITY is set, the default will be 64, which is larger than the default of 32 in mbedtls (when not using TLS 1.3). If a PSK with length greater than 32 is used, we will not alert that the PSK is too large, but the connection will fail due to the mbedtls max length.
This updates to make the default match the 32 bytes used by mbedtls. This ensures that users will not encounter connection issues unless they have modified the max length, which now has a disclaimer that updating MBEDTLS_PSK_MAX_LEN may be required as well.
Ref: …
=> examples: zephyr: use 32 as default PSK max length

.github/workflows/reports-allure-publish.yml
Change back to upstream GH action for Allure Reports publishing now that changes we needed are merged.
=> workflows: use upstream action for reports-allure-publish

include/golioth/fw_update.h, port/esp_idf/fw_update_esp_idf.c, port/modus_toolbox/fw_update_mcuboot.c, port/zephyr/golioth_fw_zephyr.c, src/fw_update.c
When an error occurs during a firmware block download, the download will now resume from that block instead of starting from the beginning.
Each block is included in a sha256 hash calculation during the download and compared to the server-supplied hash to verify a successful download. This comparison is made while the data is in RAM, before it is written to flash.
If a flash write error occurs during block download, the firmware download is considered a failure and will not try to resume from that block.
Resolves: https://github.com/golioth/firmware-issue-tracker/issues/688
Resolves: https://github.com/golioth/firmware-issue-tracker/issues/698
=> fw_update: add resume download functionality

src/coap_client.c, src/coap_client.h, src/coap_client_libcoap.c, src/coap_client_libcoap.h, src/coap_client_zephyr.c, src/coap_client_zephyr.h, src/zephyr_coap_req.c, src/zephyr_coap_req.h
Remove typedefs defined in `src/coap_client.h` to align with our coding standard
=> Replace typedefs

include/golioth/ota.h
We need more reason codes to better indicate behavior added to the SDK. This PR seeks alignment from the firmware and cloud teams as the codes will need to be added to both the SDK and the Console.
Please view the comments for each new code in the commit. I think these should align with what is shown in the console so adding your thoughts on those lines is appreciated!
1. Firmware download begins, current behavior remains the same:
```
GOLIOTH_OTA_STATE_DOWNLOADING : GOLIOTH_OTA_REASON_READY
```
2. Failure while downloading a block (client restart or request timeout):
```
GOLIOTH_OTA_STATE_DOWNLOADING : GOLIOTH_OTA_REASON_BLOCK_FAILED
```
3. Previous failure does not cause the download to fail... we will immediately try to resume. This combined with step two means that repeated block …
=> ota: add reason codes related to fw_update

port/esp_idf/components/golioth_sdk/CMakeLists.txt, port/esp_idf/golioth_sys_espidf.c, port/freertos/golioth_sys_freertos.c, port/modus_toolbox/golioth_port_config.h, port/modus_toolbox/golioth_sys_modus_toolbox.c
The sha256 API was implemented in the FreeRTOS port layer. It used mbedtls to calculate the hash, but different versions of mbedtls can be used with FreeRTOS.
This PR moves the golioth_sys_sha256_* APIs out of FreeRTOS and into ESP-IDF and ModusToolbox ports. This solves a function name issue with the older version of mbedtls in ModusToolbox. It also makes it easier for custom ports to implement their own hashing.
=> ports: move golioth_sys_sha256_* APIs out of FreeRTOS and into platforms

examples/zephyr/common/wifi.c
So far `net_if_get_default()` was used. This is fine in case of all platforms
that have single network interface. However for platforms with multiple
network interfaces (e.g. WiFi and Ethernet) it would not work.
Make sure to always get WiFi network interface, in case there are multiple
available on used hardware platform.
=> examples: zephyr: wifi: make sure to get WiFi interface type

port/zephyr/CMakeLists.txt
Information about ZCBOR version at buildsystem and C level is no longer
needed, so drop that from cmake file.
This reverts commit 82203e723e4edfbcc4fc83ec11e8f1628ba2d7cd.
=> Revert "zephyr: zcbor: parse version and expose ZCBOR_VERSION_{MAJOR,MINOR}"

src/fw_update.c
Allow a new manifest to be received regardless of the state of the fw_update thread. This removes the need to drop a new manifest during the downloading step. To make this possible, a new version of the target component is copied from the manifest for the fw_update thread to use during the download process.
Resolves: https://github.com/golioth/firmware-issue-tracker/issues/748
=> fw_update: do not drop manifests based on state; store target components

src/fw_update.c
Resolves https://github.com/golioth/firmware-issue-tracker/issues/699
=> fw_update: implement retry with backoff

.github/workflows/clean-ci-project.yml, scripts/ci/clean_ci_project
Add a workflow that finds and remove Devices, Certificates, Cohorts, Release, and Tags that are more that 1 day old. This workflow runs once per day.
This test was run with `--days-old 0.001` (about 90 seconds) but the default in this commit is 1 day.
Resolves: https://github.com/golioth/firmware-issue-tracker/issues/740
=> workflows: add Clean CI Project and run once per day

.github/workflows/ci-clean-project.yml, .github/workflows/ci-gitlint.yml, .github/workflows/ci-lint-build.yml, .github/workflows/ci-pre-commit.yml, .github/workflows/ci-yamllint.yml, .github/workflows/doc-firebase-doxygen-main.yml, .github/workflows/doc-firebase-doxygen-pr.yml, .github/workflows/hil-integration-esp-idf.yml, .github/workflows/hil-integration-linux.yml, .github/workflows/hil-integration-nsim.yml, .github/workflows/hil-integration-zephyr.yml, .github/workflows/hil-sample-esp-idf.yml, .github/workflows/hil-sample-nsim.yml, .github/workflows/hil-sample-zephyr.yml, .github/workflows/report-allure-publish.yml, .github/workflows/report-summary-publish.yml, .github/workflows/test-comprehensive.yml, .github/workflows/test-recurring.yml, .github/workflows/trigger-push-and-schedule.yml
Rename and retitle all tests for better organization. This delivers a more uniform list on the GitHub Actions page, and groups workflow files by functionality.
- Use categories as prefix: ci, doc, hil, report, test, trigger
- Normalize on '-' instead of '_' in filenames
- Replace 'test' in filenames with 'integration' to differentiate from 'sample'
=> workflows: standardize titles and filenames

.github/workflows/ci-clean-project.yml, .github/workflows/ci-gitlint.yml, .github/workflows/ci-lint-build.yml, .github/workflows/ci-pre-commit.yml, .github/workflows/ci-yamllint.yml, .github/workflows/doc-firebase-doxygen-main.yml, .github/workflows/doc-firebase-doxygen-pr.yml, .github/workflows/hil-integration-esp-idf.yml, .github/workflows/hil-integration-linux.yml, .github/workflows/hil-integration-nsim.yml, .github/workflows/hil-integration-zephyr.yml, .github/workflows/hil-sample-esp-idf.yml, .github/workflows/hil-sample-nsim.yml, .github/workflows/hil-sample-zephyr.yml, .github/workflows/report-allure-publish.yml, .github/workflows/report-summary-publish.yml, .github/workflows/test-comprehensive.yml
The GitHub Actions cloud runner `ubuntu-latest` images are moving from Ubuntu 22.04 LTS to Ubuntu 24.04 LTS. We should be pinning these anyway, so we'll pin to Ubuntu 24.04 LTS. This also suppresses a warning message in the GitHub UI.
The Modus Toolbox build workflow will remain pinned to Ubuntu 22.04 for now, as it does not build without modification on Ubuntu 24.04. Ubuntu 22.04 is supported for another 2 years.
=> ci: pin github runners to ubuntu 24.04

.github/workflows/hil-integration-zephyr.yml
When creating the report summary, we were downloading the test results for all boards, instead of just the one we're testing. This caused results to be recorded multiple times, and for boards which completed testing later to include results from boards which completed testing earlier.
In this screenshot you can see how the ESP32 Zephyr integration test includes results for many more runs than it should:
=> ci: zephyr_integration: avoid collision in test report artifacts

.github/workflows/hil-sample-esp-idf.yml, examples/esp_idf/certificate_auth/main/CMakeLists.txt, examples/esp_idf/certificate_auth/pytest/README.md, examples/esp_idf/certificate_auth/pytest/conftest.py, examples/esp_idf/certificate_auth/pytest/test_sample.py
Add the certificate_auth sample to the ESP-IDF testing suite.
=> ESP-IDF: add certificate_auth to sample tests

.github/workflows/report-allure-publish.yml
Specify most recent minor version of action to ensure the fixes for links back to the workflow associated with a report is available.
=> workflow: use specific version of allure-report-action

.github/workflows/hil-integration-esp-idf.yml, .github/workflows/hil-sample-esp-idf.yml, CHANGELOG.md, README.md, include/golioth/golioth_sys.h, port/esp_idf/libcoap/include/coap_config_posix.h
SDK Changes Due to this Update:
- Guard LOG_COLOR* defines with #ifndef
- Espressif changed the defines so they no longer exactly match those in the Golioth SDK. They also turned off log    color by default, citing that `idf.py monitor` now handles colorization.
- Guard IN6_IS_ADDR_V4MAPPED(a) with #ifndef
- The macro was compared between the header in the Golioth Firmware SDK and the one in the esp-lwip repo and found to be functionally equivalent.
Resolves https://github.com/golioth/firmware-issue-tracker/issues/734
=> Update ESP-IDF to v5.4

.github/workflows/hil-sample-esp-idf.yml
This job was added after the ubuntu version was pinned for all of the other jobs. Pin the ubuntu version used in GitHub Actions to ensure stability and suppress warnings in the GitHub UI.
=> ci: pin ubuntu version for esp-idf-device-name job

.github/workflows/hil-integration-linux.yml, .github/workflows/hil-integration-zephyr.yml
When we split the test job into a matrix of jobs, the summary steps were moved to their own job. This job needs to be run after both success and failures of the test jobs to ensure that the summary reflects any test failures.
=> ci: ensure summary step runs after failures

.github/workflows/hil-integration-esp-idf.yml, .github/workflows/hil-integration-linux.yml, .github/workflows/hil-integration-nsim.yml, .github/workflows/hil-integration-zephyr.yml, .github/workflows/hil-sample-esp-idf.yml, .github/workflows/hil-sample-nsim.yml, .github/workflows/hil-sample-zephyr.yml, .github/workflows/report-allure-publish.yml, .github/workflows/test-comprehensive.yml, .github/workflows/test-recurring.yml
Prefer `success() || failure()` instead of `always()` for workflow steps related to storing artifacts, and generating and storing test reports. This ensures that those steps won't run when a workflow is cancelled. This will allow runs to be cancelled faster, and also prevents incomplete results from being included in test reports.
Note that the steps for erasing boards and powering down USB hubs are left as `always()` so that we still put the runners into our preferred idle state after cancelling a run.
=> ci: don't store artifacts while cancelling workflows

west-ncs.yml
This is the latest NCS stable release.
=> bump NCS to 2.9.0

tests/hil/tests/settings/test.c, tests/hil/tests/settings/test_settings.py
When registering settings during the HIL test, we get a flood of log messages. On some platforms this can overwhelm the log buffer and lead to dropped messages. If one of those dropped messages is the connection message that the test scripts wait for, the test will fail.
Now, we add a small delay after registering the settings to give time for the log buffer to flush, and then send a new "settings registration complete" message for the test script to key off of. This ensures the test script receives the message, and increases the stability of the test.
Resolves golioth/firmware-issue-tracker#737
=> tests: settings: delay after connection for log flush

.ci-west-ncs.yml
We no longer use qcbor, having replaced it with zcbor.
=> west: ci-ncs: drop qcbor

src/fw_update.c
Fixes small misspelling in log message when downloaded image hash does not match the hash in the manifest.
=> fw_update: fix log message on hash mismatch

port/zephyr/golioth_version_boot_msg.c
Fix typo in #define for boot version.
=> port: zephyr: fix typo

examples/esp_idf/fw_update/README.md
Cleans up a few typos and formatting issues in the fw_update README.md.
=> examples: esp_idf: clean up fw_update README.md

port/esp_idf/golioth_sys_espidf.c, port/modus_toolbox/golioth_sys_modus_toolbox.c, port/zephyr/golioth_sys_zephyr.c
`mbedtls_sha256_free()` [does not](https://github.com/Mbed-TLS/mbedtls/blob/107ea89daaefb9867ea9121002fbbdf926780e98/library/sha256.c#L230-L237) free memory, it only zeroes out the SHA context struct.
=> port: fix memory leak in SHA256

include/golioth/client.h, include/golioth/stream.h, src/coap_blockwise.c, src/coap_blockwise.h, src/coap_client.h, src/coap_client_libcoap.c, src/coap_client_zephyr.c, src/stream.c, tests/hil/tests/stream/test.c, tests/hil/tests/stream/test_stream.py
Multi-block upload implements a blockwise upload using repeated API calls:
1. Create a context
2. Call the multi-block set API once for each block in the upload
3. Destroy the context
=> Implement multi-block upload

examples/zephyr/location/pytest/conftest.py, examples/zephyr/location/pytest/test_sample.py, examples/zephyr/location/sample.yaml
There are 3 runtime tests:
* cellular + wifi
* cellular only
* wifi
all executed using `native_sim` platform and playback data.
Supersedes: #725
=> location: twister+pytest test for native_sim and playback data

.github/workflows/hil-sample-nsim.yml, .github/workflows/hil-sample-zephyr.yml
This changes following report:
```
INFO    - Total complete:    1/   4   25%  built (not run):    1, filtered:    0, failed:    0, error:    0
INFO    - Total complete:    2/   4   50%  built (not run):    1, filtered:    0, failed:    0, error:    0
INFO    - Total complete:    3/   4   75%  built (not run):    1, filtered:    0, failed:    0, error:    0
INFO    - Total complete:    4/   4  100%  built (not run):    1, filtered:    0, failed:    0, error:    0
INFO    - 4 test scenarios (4 configurations) selected, 0 configurations filtered (0 by static filter, 0 at runtime).
INFO    - 3 of 4 executed test configurations passed (75.00%), 1 built (not run), 0 failed, 0 errored, with no warnings in 49.12 seconds.
INFO    - 3 of 3 executed test cases passed (100.00%) on 1 out of total 860 …
```
=> ci: increase twister verbosity with single -v flag

.clang-format
clang-format 20.1.0 [adds C as a language instead of treating it as C++](https://releases.llvm.org/20.1.0/tools/clang/docs/ReleaseNotes.html#clang-format). This breaks our clang-format configuration, which scopes the configuration to Cpp at the start of the config file, making the lint action claim that C isn't supported by the configuration.
Example failure in CI: https://github.com/golioth/golioth-firmware-sdk/actions/runs/13788107438/job/38560847890
=> Clang format: Remove Cpp language specifier

examples/zephyr/common/wifi.c
Fixes https://scan8.scan.coverity.com/#/project-view/62270/15696?selectedIssue=544186
=> examples: zephyr: common: wifi: remove dead code

west-ncs.yml, west-zephyr.yml
There are no custom commands anymore, so drop that entry from west manifests.
This is a followup to commit 88ff1db76bd4 ("scripts: drop downstream 'west patch' command").
=> west: drop self/west-commands

src/coap_blockwise.c
The `path` member of the blockwise_transfer context is freed when the "finish" function is called. Test the context for NULL before trying to free the member.
=> coap_blockwise: test for null before dereferencing pointer

include/golioth/ota.h, src/coap_blockwise.h, src/fw_update.c, src/ota.c, tests/hil/tests/ota/test.c
Mark payload data as const in block write callbacks.
=> blockwise: const correctness

examples/zephyr/certificate_provisioning/README.md, examples/zephyr/certificate_provisioning/pytest/test_sample.py, examples/zephyr/certificate_provisioning/src/main.c
Use shorter file names, so it is quicker to parse and understand what is
the role of each. Additionally this allows to deduplicate part of the
testing code.
=> examples: zephyr: certificate_provisioning: use shorter file names

include/golioth/ota.h, port/linux/golioth_sys_linux.c, src/ota.c, tests/hil/tests/ota/test.c, tests/hil/tests/ota/test_ota.py
add `golioth_ota_get_manifest_async()` as an alternative to registering an observation for OTA manifest updates.
add test for `golioth_ota_get_manifest_async()`
resolves https://github.com/golioth/firmware-issue-tracker/issues/787
=> ota: add manifest get command

CHANGELOG.md, examples/zephyr/common/Kconfig.defconfig, port/esp_idf/components/golioth_sdk/Kconfig, port/zephyr/Kconfig, src/Kconfig.coap, tests/hil/platform/zephyr/prj.conf
Make `GOLIOTH_COAP_MAX_PATH_LEN` an automatic setting that cannot be changed by the user and base its default on the Zephyr CoAP setting. This reduces the default from 39 characters down to 12 characters. Users may change this value using the symbols provided by Zephyr CoAP:
- CONFIG_COAP_EXTENDED_OPTIONS_LEN=y
- CONFIG_COAP_EXTENDED_OPTIONS_LEN_VALUE=39
In Zephyr, the GOLIOTH_COAP_MAX_PATH_LEN symbol defaulted to 39 characters while Zephyr's CoAP library defaulted to 12 characters. Sending a single stream call with a path name >12 worked as expected. However, when sending a blockwise stream using a path name between 13 and 39 characters the Golioth check would pass, the Zephyr library would create the coap packet, but subsequent CoAP operations to prepare the block for upload would …
=> zephyr: coap: limit path length based on Zephyr CoAP library

.github/workflows/hil-sample-zephyr.yml, examples/zephyr/certificate_provisioning/CMakeLists.txt, examples/zephyr/certificate_provisioning/generate-lfs-image.py, examples/zephyr/certificate_provisioning/pytest/test_sample.py
Make sure to reformat LittleFS partition by overriding first 2 (erase)
blocks of the partition.
=> examples: zephyr: cert_provisioning: override LFS partition before boot

.github/workflows/hil-integration-esp-idf.yml, .github/workflows/hil-integration-linux.yml, .github/workflows/hil-integration-nsim.yml, .github/workflows/hil-integration-zephyr.yml, .github/workflows/hil-sample-esp-idf.yml, tests/hil/platform/zephyr/testcase.yaml, tests/hil/scripts/pytest-hil/pytest_hil/plugin.py
It is very inconvenient to run all tests by hand, as this involves
multi-step process:
* build firmware
* run pytest script with following parameters passed by hand:
* fw_image
* board_name (derived from build command, but not the same)
* serial port
* serial number (for flashing)
Most of above steps are already automated with twister and pytest harness.
Support running existing pytest tests from within twister. As a result it
is possible to run single command to build, test and reuse
hardware-map.yaml (with serial port, serial number, etc.) defined for
Zephyr samples testing purposes.
=> tests/hil: zephyr: support running with twister

examples/zephyr/certificate_provisioning/pytest/conftest.py, examples/zephyr/certificate_provisioning/sample.yaml
Configure different UDP port for second testcase, so that running
certificate_provisioning for native_sim won't run into "unable to bind UDP
port" because of two tests being exeucuted in parallel.
=> examples: zephyr: cert_provisioning: use different UDP ports

include/golioth/ota.h, src/coap_blockwise.c, src/coap_blockwise.h, src/fw_update.c, src/ota.c, tests/hil/tests/ota/test.c
This changes the golioth_coap_blockwise_get to be non-blocking, with block write callbacks executed on the coap client thread. Users are responsible for ensuring that they do not block the client thread unduly.
A second commit in this PR also reworks and simplifies the way that block retries are executed in the fw_update module. This simplifies program flow, removes a `while(1)` loop, and reduces the amount of state that has to be moved between the callback and the thread. One of the consequences is that we no longer report to the OTA state service when we retry a block download. I think that's acceptable and even desirable because:
- Fundamentally, the state of the device has not changed (it is still attempting to download the package)
- The reason for logging this is to provide some …
=> Non blocking blockwise get

.ci-west-ncs.yml, .github/workflows/hil-sample-zephyr.yml, .github/workflows/test-comprehensive.yml, examples/zephyr/certificate_provisioning/generate-lfs-image.py, examples/zephyr/certificate_provisioning/pytest/test_sample.py, examples/zephyr/fw_update/pytest/conftest.py, examples/zephyr/hello_nrf91_offloaded/pytest/conftest.py, west-ncs.yml
In some cases there are still old artifacts on the filesystem on
self-hosted runners. They are no harm for testing, but they do occupy space
and they are archived as artifacts after HIL testing finishes.
Make sure that 'twister-out' is removed before extracting new artifacts.
This reduces confusion when inspecting failed jobs.
=> ci: remove 'twister-out' before extracting new artifacts

src/coap_blockwise.c
Fix a bug where requesting the next block could silently fail. Now, if we fail to submit a request for a block, we end the download and alert the application.
Fixes golioth/firmware-issue-tracker#803
=> blockwise: handle errors when requesting next block

port/zephyr/golioth_sys_zephyr.c, src/coap_client_libcoap.c, tests/hil/tests/connection/test.c, tests/hil/tests/connection/test_connection.py
Cancelling a scheduled work item is not immediate, and scheduling
an already scheduled work item has no effect. So the previous
strategy of resetting timers by first cancelling and then
immediately scheduling them fails.
Instead we use the k_work_reschedule() API, which works on
both scheduled and scheduled work items.
Additionally, we now properly supply return values for timer
functions.
Fixes golioth/firmware-issue-tracker#805
=> Fix zephyr timer reset

src/coap_client_zephyr.c
- Rename the static `flags` variable (used for stopping the client) to `client_flags` to disambiguate it from the local `flags` variable used in various functions for socket flags.
- Zephyr's atomic functions expect an array of `atomic_t`, but we were passing a pointer to a single `atomic_t`, which worked in practice because the number of flags was less than the size of `atomic_t`, but this triggered an issue in Coverity for potential out-of-bounds memory access. Instead, use Zephyr's `ATOMIC_DEFINE()` macro to define the `client_flags` variable, as recommended.
https://scan8.scan.coverity.com/#/project-view/62270/15696?selectedIssue=544162
=> Clean atomics in zephyr client

src/coap_blockwise.c
The post_block and get_block contexts had been including a reference to a transfer context struct that is allocated separately. We can remove an allocation and simplify error handling by including the full struct as a member rather than including a pointer.
This also fixes a structurally dead code report from Coverity (that was also actually a memory leak).
https://scan8.scan.coverity.com/#/project-view/62270/15696?selectedIssue=553971
=> blockwise: include transfer context struct by value

port/esp_idf/components/golioth_sdk/CMakeLists.txt, port/linux/golioth_sdk/CMakeLists.txt
This allows for testing the Gateway service on these platforms, even if we're not building gateways on them. This is useful for testing how libcoap performs with some of the changes we're making to the client to support gatewawy work.
=> port: add gateway service to Linux and ESP-IDF

src/coap_client_zephyr.c, src/zephyr_coap_req.c, src/zephyr_coap_utils.c
Replace LOG_XXX() with GLTH_LOGX() calls. This brings files in line with the standard for cross-platform files. Even though these are currently Zephyr-specific files, this ensures that these may be enabled/disabled using CONFIG_GOLIOTH_DEBUG_LOG in the same way as all other files.
resolves https://github.com/golioth/firmware-issue-tracker/issues/816
=> src: replace Zephyr style log with cross-platform macros

src/lightdb_state.c, src/ota.c, src/settings.c
These errors are due to using snprintf() but not directly including stdio.h. In lightdb_state.c and ota.c we now include stdio.h. In settings.c we rework logging to remove the snprintf call, which also recovers some resources when logging is disabled.
=> Fix undefined reference warnings when debug logging is turned off

examples/esp_idf/hello/pytest/test_sample.py, examples/zephyr/hello/pytest/test_sample.py, examples/zephyr/hello_nrf91_offloaded/pytest/test_sample.py, examples/zephyr/logging/pytest/test_sample.py
`datetime.utcnow()` is deprecated since Python 3.12.
See https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow
=> examples: replace deprecated datetime.utcnow()
