- src/golioth_settings.c
Errors for individual settings are now reported in the "errors" array of the settings status report, per the latest backend spec.
> settings: support for errors array in .c/status

- .github/workflows/test_esp32s3.yml
- examples/esp_idf/test/main/app_main.c
- examples/esp_idf/test/verify.py
RPC is tested using the golioth REST API, getting the specific project, device, and API key from credentials.yml.
> test: add RPC test

- .gitmodules
- port/esp_idf/components/golioth_sdk/CMakeLists.txt
- port/esp_idf/components/heatshrink/CMakeLists.txt
- port/esp_idf/components/libcoap/CMakeLists.txt
- port/esp_idf/fw_update_esp_idf.c
- port/linux/fw_update_linux.c
- port/linux/golioth_sdk/CMakeLists.txt
- src/golioth_fw_update.c
- src/golioth_ota.c
- src/include/golioth_fw_update.h
- src/include/golioth_ota.h
This PR is a series of commits needed to implement a proof-of-concept for OTA download compression.
> Compression for OTA downloads

- port/linux/golioth_sys_linux.c
- src/golioth_coap_client.c
A handful of issues I fixed while troubleshooting an RPC observation issue. 
See commit messages for description.
> CoAP option fixes, linux msleep fix

- src/golioth_coap_client.c
A couple of minor changes (see commit descriptions)
> Log the PSK-ID when session created, refactor client connection event

- src/golioth_coap_client.c
- src/golioth_lightdb.c
- src/golioth_ringbuf.c
A few minor fixes to resolves warnings emitted by cppcheck.
> Fixes of warnings emitted by cppcheck

- .github/workflows/lint_build_unit_test.yml
- examples/modus_toolbox/golioth_basics/golioth_app/.cyignore
- examples/modus_toolbox/golioth_basics/golioth_app/source/credentials.inc.template
Job will download ModusToolbox (~ 1 GB), install it, then build the golioth_basics project.
> .github: add modus_toolbox_build job

- examples/esp_idf/common/shell.c
Before this change, if an unknown key was entered in the settings command, the string "unknown" would be used as the key when reading/writing NVS on the device. There was no error returned to the user (appeared successful). This allowed users to enter invalid keys (like "wifi/password", a common mistake), and be led to believe the key was set successfully, when in fact it was not.
This changes moves the known keys into a lookup table, then returns an error if the key entered by the user isn't in the lookup table.
> esp_idf,shell: verify key before accessing NVS

- examples/modus_toolbox/golioth_basics/golioth_app/Makefile
- port/esp_idf/components/heatshrink/CMakeLists.txt
- port/linux/golioth_sdk/CMakeLists.txt
- src/golioth_fw_block_processor.c
- src/golioth_fw_update.c
- src/priv_include/golioth_fw_block_processor.h
* heatshrink: update to latest develop branch 
* fw_block_processor: use static heatshrink decoder
> fw_update: use static heatshrink decoder

- src/golioth_coap_client.c
If a CoAP client makes a block2 request for a resource that is less than the size of a block (e.g. < 1024 bytes), the Golioth server will not include the BLOCK2 option in the response.
Logic for handling block2 requests has been updated accordingly, to allow for a possible NULL return from
coap_check_option(COAP_OPTION_BLOCK2).
> coap_client: allow for no block2 option in block response

- src/golioth_settings.c
All numbers in JSON are doubles, there is no distinction between integer and floating point numbers, but we treat floats and integers as separate types for our settings. Previously, we tested whether or not a number was a float by examining the fractional part of the number, classifying it as a float if it was greater than Epsilon. This meant that whole numbers would always be classified as integers (i.e. 11.0). Instead, we now check the type that the user gave when they registered the setting callback with the SDK. We still check the fractional part of the number, but only to reject floating point values for integer type settings.
> settings: allow float-type settings to be whole numbers

- README.md
Remove experimental features (FW compression, delta updates, remote shell)
Add Zephyr column
> readme: update supported features table

- port/zephyr/golioth_sys_zephyr.c
Timer handlers can be executed in an interrupt context if they are fired from hardware timers. Scheduling the timer handlers on the work thread ensures that we are executing in a thread context and not an interrupt context.
I consider this to be a temporary fix. Long term, I'd like all SDK functionality to execute on the CoAP client thread, but this is a smaller fix for now.
Fixes https://github.com/golioth/firmware-issue-tracker/issues/247
> port: zephyr: use work thread for timer handlers

- examples/esp_idf/README.md
- examples/esp_idf/certificate_auth/README.md
Update readmes for ESP-IDF examples to reflect most current code changes.
> Update esp idf readmes

- examples/zephyr/README.md
- examples/zephyr/golioth_basics/README.md
* Document how to use the Zephyr beta on the Firmware SDK
* Add basic config/flashing info to zephyr golioth_basics (usage and console output will be added in the future)
> Add zephyr beta readme

- include/golioth_sys.h
- port/freertos/golioth_sys_freertos.c
- port/linux/golioth_sys_linux.c
- port/zephyr/golioth_sys_zephyr.c
- src/golioth_coap_client.c
- src/golioth_fw_update.c
Resolves golioth/firmware-issue-tracker#219
> port: pass structs by reference in golioth_sys_* apis

- examples/zephyr/logging/pytest/conftest.py
- examples/zephyr/logging/pytest/test_sample.py
- examples/zephyr/logging/sample.yaml
Check that each type of log massage is received, verifying both message text and log level.
> zephyr: add test for the logging sample

- .github/workflows/hil_sample_zephyr.yml
- examples/zephyr/fw_update/pytest/conftest.py
- examples/zephyr/fw_update/pytest/test_sample.py
- examples/zephyr/fw_update/sample.yaml
Test OTA by running the fw_update example on all available HIL board types.
* This targets prod so I'm basing this merge on the `test_against_prod` branch
* nRF9160 currently failing but that's actually the test catching an issue with our SDK
> Add fw_update sample test

- .github/workflows/hil_sample_zephyr.yml
- examples/zephyr/certificate_provisioning/pytest/conftest.py
- examples/zephyr/certificate_provisioning/pytest/test_sample.py
- examples/zephyr/certificate_provisioning/sample.yaml
- examples/zephyr/certificate_provisioning/src/main.c
* HIL test for the certificate provisioning examples
* Install mcumgr on runners to facilitate the test
> Add certificate provisioning test

- include/golioth/settings.h
- src/settings.c
Add function to register Settings service for string type.
> settings: add setting register for string type

- src/coap_client_zephyr.c
When connected, set client->session_connected to true
> coap_client_zephr: set session_connected

- docs/Porting_Guide.md
I had started a full rewrite of this guide, but it was a bigger task than I anticipated, so instead we'll just update what's necessary to make the current guide reflect changes made recently.
> docs: update porting guide

- .github/workflows/hil_sample_esp-idf.yml
- .github/workflows/hil_test_esp-idf.yml
- .github/workflows/lint_build_unit_test.yml
- .github/workflows/test_esp32s3.yml
- examples/esp_idf/README.md
Resolves golioth/firmware-issue-tracker#469
> esp-idf: bump version to 5.2.1

- examples/zephyr/fw_update/pytest/README.md
Document how to build and stage artifacts for CI fw_update testing.
> ci: zephyr: document fw_update artifact build

- port/zephyr/golioth_log_zephyr.c
The Zephyr port was using log_backend_enable()/disable() to prevent logs from generating CoAP events when not connected to Golioth. This interferes with applications using the log_backend_activate()/deactivate() functions to enable or disable backend logging at runtime.
This commit adds an `enabled` flag to the backend context which is used to determine if a log should be processed. This way, the SDK can disable/enable backend logging when the connection status changes, while retaining the ability for applications to control the backend through normal Zephyr logging management functions.
The first time a connection to Golioth is established, the backend will be automatically activated. If your application needs to deactivate this backend at runtime, do so only after the first connection …
> Use flags to control Golioth logging backend

- .github/workflows/hil_sample_esp-idf.yml
- .github/workflows/hil_sample_zephyr.yml
- .github/workflows/hil_test_esp-idf.yml
- .github/workflows/hil_test_linux.yml
- .github/workflows/hil_test_zephyr.yml
Adds workflow_dispatch trigger to HIL sub-workflows such that they can be invoked individually.
> ci: support workflow_dispatch on HIL sub-workflows

- src/fw_update.c
If registering the firmware rollout observation fails, retry up to 3 times.
> fw update: retry firmware observation

- CONTRIBUTING.md
- docs/Style_Guide.md
- [Link to Golioth Forums for discussions](https://github.com/golioth/golioth-firmware-sdk/pull/472/commits/eed4aa9fde9c5998dcbd5394f4a3da88bf0475ec)
- [Update Style Guide to match current development practices](https://github.com/golioth/golioth-firmware-sdk/pull/472/commits/a977d08f014f15e0083cbee2f8d135a669bd6ae0)
> Updates to contributor docs

- src/fw_block_processor.c
Retry up to three times if a block download request returns an error.
Tested with esp-idf by switching the AP on and off, this prevents the download from failing:
```
E (65778) libcoap: coap_socket_send: Host is unreachable
W (65778) libcoap: coap_netif_dgrm_write failed (-1 != 362)
E (65778) libcoap: coap_socket_send: Host is unreachable
W (65788) libcoap: coap_netif_dgrm_write failed (-1 != 543)
I (67148) example_wifi: retry to connect to the AP
I (67148) example_wifi: connect to the AP fail
I (68218) esp_netif_handlers: sta ip: 192.168.40.51, mask: 255.255.255.0, gw: 192.168.40.47
I (68218) example_wifi: WiFi Connected. Got IP:192.168.40.51
W (70058) libcoap: ***0.0.0.0:63925 <-> 34.135.90.112:5684 DTLS: Alert '49': Access was denied
E (70058) golioth_coap_client_libcoap: Received nack …
```
> fw_update: add retry to block download

- src/coap_client_libcoap.c
- src/coap_client_zephyr.c
Check CONFIG_GOLIOTH_MAX_NUM_OBSERVATIONS before registering a new coap observation.
> Obey limit when adding observations

- src/coap_blockwise.c
- src/coap_blockwise.h
This is the same blockwise upload commit that was approved today for merging into a temporary branch rsv/temp_blockwise_base_branch. However, the temporary branch's history got messed up after I tried to rebase it and now has too many conflicts with main. So I created this new branch (rsv/golioth_blockwise_post) from main and cherry-picked the blockwise upload module commit 3033124 for a cleaner merge.
> Blockwise Uploads Module with golioth_blockwise_post API

- include/golioth/client.h
- src/coap_client_libcoap.c
- src/coap_client_zephyr.c
resolves https://github.com/golioth/firmware-issue-tracker/issues/502
> coap: add octet stream content type for binary data

- src/coap_blockwise.c
The blocking APIs in the CoAP client create and destroy a semaphore each time they are called. For a complete blockwise transfer, we could call these APIs thousands of times. To avoid creating and destroying a semaphore each time, we instead manage the blocking in the blockwise transfers module, which now uses the non-blocking APIs. This allows us to create and destroy the semaphore just once for the complete blockwise transfer, rather than for each block.
Also, rename the `status` member of the context struct to `response_status` to better reflect how it is used.
Resolves golioth/firmware-issue-tracker#581
> coap_blockwise: use non-blocking APIs for CoAP operations

- .github/workflows/hil_sample_zephyr.yml
- .github/workflows/hil_test_zephyr.yml
- .github/workflows/hil_tests.yml
- examples/zephyr/certificate_provisioning/sample.yaml
- examples/zephyr/fw_update/sample.yaml
- patches/west-zephyr/zephyr/0040-twister-add-flash-before-option.patch
- patches/west-zephyr/zephyr/0041-twister-fix-serial-connection-for-flash_before.patch
- patches/west-zephyr/zephyr/0042-boards-rak5010_nrf52840-add-blackmagicprobe.patch
- patches/west-zephyr/zephyr/0043-twister-harness-pytest-Check-exist-of-the-runner_par.patch
Add support for the RAK5010 in HIL testing.
resolves https://github.com/golioth/firmware-issue-tracker/issues/530
> Add rak5010 to HIL testing

- include/golioth/stream.h
- stream: update doxygen for read block callback
> Add more documentation to read coap block callback

- examples/esp_idf/common/README.md
- examples/zephyr/common/README.md
Resolves golioth/firmware-issue-tracker#492
> examples: Add READMEs for common code

- include/golioth/client.h
- include/golioth/ota.h
resolves https://github.com/golioth/firmware-issue-tracker/issues/611
> Add doxygen to block-related functions

- .github/workflows/hil_sample_esp-idf.yml
- .github/workflows/hil_test_esp-idf.yml
- .github/workflows/lint_build_unit_test.yml
- README.md
- examples/esp_idf/README.md
Resolves golioth/firmware-issue-tracker#602
> Esp idf v5.3

- .github/workflows/hil_test_esp-idf.yml
- .github/workflows/hil_test_linux.yml
- .github/workflows/hil_test_zephyr.yml
- .github/workflows/hil_tests.yml
- .github/workflows/reports-summary-publish.yml
- tests/hil/tests/connection/conftest.py
- tests/hil/tests/lightdb/conftest.py
- tests/hil/tests/ota/conftest.py
- tests/hil/tests/rpc/conftest.py
- tests/hil/tests/settings/conftest.py
- tests/hil/tests/stream/conftest.py
Add summary for all integration tests to the existing summary for all sample tests.
Resolves https://github.com/golioth/firmware-issue-tracker/issues/671
Resolves https://github.com/golioth/firmware-issue-tracker/issues/647
Resolves https://github.com/golioth/firmware-issue-tracker/issues/648
> Add hil integration summary

- .github/workflows/reports-allure-publish.yml
Add a link to view the Allure report to the summary section of the workflow.
Resolves https://github.com/golioth/firmware-issue-tracker/issues/676
> workflows: add Allure report link to workflow summary

- .codecov.yml
- .github/workflows/hil_tests.yml
- README.md
Upload coverage to Codecov to see code coverage change over time.
> ci: hil: upload coverage to Codecov

- .github/workflows/hil_test_trigger.yml
- .github/workflows/tests.yml
This workflow includes unit tests, so let's rename it.
> ci: rename 'hil_tests' workflow to 'tests'

- .github/workflows/reports-allure-publish.yml
Remove the push trigger which is left over from testing
> workflows: allure: remove on push

- .github/workflows/tests.yml
- tests/hil/scripts/pytest-hil/plugin.py
- Fix issues with naming and collection of nsim sample tests
- Add Allure report and summary generation/collection of nsim hil tests
resolves https://github.com/golioth/firmware-issue-tracker/issues/714
> HIL: Collect reports and summaries for native sim

- tests/hil/platform/zephyr/CMakeLists.txt
- tests/hil/platform/zephyr/boards/nrf9160dk_nrf9160_ns.conf
Noticed a couple of small issues while testing NCS 2.8 that also apply to earlier versions.
> Nrf91 hil fixes

- src/fw_update.c
resolves https://github.com/golioth/firmware-issue-tracker/issues/736
> fw_update: Stability improvements to reporting state/reason

- README.md
- examples/zephyr/README.md
Before on the left, after on the right:
> README: use GitHub formatting for admonitions

- .github/workflows/hil-integration-esp-idf.yml
- .github/workflows/hil-integration-nsim.yml
- .github/workflows/hil-integration-zephyr.yml
- .github/workflows/hil-sample-esp-idf.yml
- .github/workflows/hil-sample-nsim.yml
- .github/workflows/hil-sample-zephyr.yml
Resolves https://github.com/golioth/firmware-issue-tracker/issues/781
> CI: update docker images; Zephyr 4.0.0, NCS 2.8.0, Zephyr SDK 0.17.0

- port/zephyr/golioth_sys_zephyr.c
Use delayable work instead of timers
> port: zephyr: use delayable work for timers

- src/coap_blockwise.c
Instead of mixing pointers to constants with pointers to allocated memory, always copy the path directly into the blockwise_transfer context struct. This ensures that the handling of the path is consistent.
> coap: blockwise: always copy path
